maidsafe/sn_client

- README.md
- src/client/mod.rs
- src/client/user_account.rs
- src/data_parser.rs
- src/id/id_type.rs
- src/id/mod.rs
- src/id/public_id_type.rs
- src/id/revocation_id_type.rs
- src/lib.rs
- src/macros.rs
Private and public IDs moved from maidsafe_types. Had to remove unsafe_code lint check because the #[allow(unsafe_code)] wont work in macros.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/100)
> MAID-1219_Ids moved from maidsafe_types

- Cargo.toml
- src/lib.rs
Adds minimal support for `use-mock-crust` feature. Enabling it currently disables the whole library, but it is necessary to make mock crust work in vault.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/230)
> Add minimal support for mock crust

- Cargo.toml
The latest regex version of 0.1.66 has been yanked from crates.io: https://crates.io/crates/regex/versions. So the build fails. This commit reverts it to the next latest regex in the crates (0.1.65)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/245)
> fix/dependency: revert to previous regex from crates

- src/dns/dns_operations/mod.rs
- src/ffi/dns/get_file.rs
Previously only registered owner and unregistered client could fetch the public dns file. A registered client could not fetch a public file that had been created by another owner. This fix aims to resolve that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/263)
> fix/dns: enable registered client to fetch public dns file

- src/ffi/mod.rs
Method name in comment `crate_account` doesn't exist, but `create_account` does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/266)
> Fix `create_account` comment typo

- src/core/client/mod.rs
Routing needs to be destroyed first for mpsc::Sender given to it to be destroyed which will trigger the exit of thread running MessageQueue and thus cause raii_joiner to exit. This order is respected in Client struct but in the stack frame of constructors (create/login functions) it was not. This fix resolves that as things that come later in the frame will be destroyed first so routing needs to come after MessageQueue because it needs to be destroyed before MessageQueue for raii_joiner to exit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/296)
> fix/unwinding: correct order of destruction

- src/core/client/non_networking_test_framework/mod.rs
- src/dns/dns_operations/mod.rs
- src/ffi/mod.rs
Make all ffi functions wrap a call to `catch_unwind`.
Note that this changes the API of some functions (returning `int64_t` rather than `u64`). Also please make sure I'm returning the correct error codes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/295)
> fix/ffi: prevent unwinding into foreign code

- src/core/client/response_getter.rs
- src/ffi/mod.rs
Exports the Client::get_account_info function to the ffi layer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/299)
> feat/ffi: add get_account_info function

- src/ffi/macros.rs
- src/ffi/mod.rs
This fixes the `not_unsafe_ptr_arg_deref` Clippy lint: Dereferencing a
pointer argument is not safe, so all functions that do that must be
declared `unsafe`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/302)
> fix/ffi: mark unsafe functions as unsafe

- examples/client_stress_test.rs
- examples/nfs_api.rs
- examples/safe_client.rs
- examples/self_authentication.rs
- examples/simulate_browser.rs
- src/core/client/mod.rs
- src/core/utility/mod.rs
- src/core/utility/test_utils.rs
- src/ffi/mod.rs
Instead of requiring user to type in all 3 of PIN, Keyword and Password, have them type only one secure pass-phrase and derive the required credentials internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/303)
> refactor/credentials: work with a single credential

- src/ffi/nfs/modify_dir.rs
- src/ffi/nfs/modify_file.rs
- src/ffi/nfs/move_dir.rs
- src/ffi/nfs/move_file.rs
Create the directory moved or copied in the network. Previously the metadata was updated, and when the directory was fetched it returned error.
Similarly in copy file the copied file must generate a new id, instead of using the same id from the source
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/312)
> fix/ffi_move: fetch copy or moved directory

- src/ffi/dns/file.rs
DNS FFI used an incorrect structure to return a file metadata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/333)
> fix/ffi: fix incorrect FileMetadata struct

- appveyor.yml
- examples/nfs_api.rs
- examples/simulate_browser.rs
- src/core/errors.rs
- src/core/structured_data_operations/versioned.rs
- src/dns/dns_operations/mod.rs
- src/ffi/dns/file.rs
- src/ffi/dns/service.rs
- src/ffi/errors.rs
- src/ffi/helper.rs
- src/ffi/launcher_config_handler.rs
- src/ffi/low_level_api/appendable_data.rs
- src/ffi/low_level_api/struct_data.rs
- src/ffi/nfs/dir.rs
- src/nfs/directory_listing.rs
- src/nfs/helper/directory_helper.rs
- src/nfs/helper/file_helper.rs
- src/nfs/metadata/directory_key.rs
- src/nfs/metadata/directory_metadata.rs
In addition, this patch optimises versions storage in versioned StructuredData. Now it stores the current version and total versions count along with a XorName of the versions list.
> feat/ffi: add low level API to get SD/AD versions

- src/ffi/low_level_api/misc.rs
New methods in the low level API: `misc_serialise_sign_key` and `misc_deserialise_sign_key`.
> feat/ffi: add API to serialise & deserialise sign keys

- src/core/client/mod.rs
- src/core/futures.rs
> refactor/core: make ok! and err! macros use boxed values

- .travis.yml
- src/ffi/app.rs
- src/ffi/errors.rs
- src/ffi/helper.rs
- src/ffi/low_level_api/cipher_opt.rs
- src/ffi/low_level_api/data_id.rs
- src/ffi/low_level_api/immut_data.rs
- src/ffi/low_level_api/misc.rs
- src/ffi/low_level_api/mod.rs
- src/ffi/macros.rs
- src/ffi/mod.rs
- src/ffi/nfs/dir.rs
- src/ffi/nfs/file.rs
- src/ffi/nfs/file_writing.rs
- src/ffi/object_cache.rs
- src/ffi/session.rs
- src/ffi/test_utils.rs
- src/nfs/helper/dir_helper.rs
* Remove Clone in Session
* Refactor low_level_api/misc and low_level_api/data_id to always use
asynchronous APIs
* Remove redundant ffi::app::drop_app function (app doesn't contain a
session now, so it doesn't need to be dropped)
> fix/ffi: fix sessions in FFI

- src/ffi/dns/file.rs
- src/ffi/launcher_config.rs
- src/ffi/low_level_api/appendable_data.rs
- src/ffi/nfs/dir.rs
- src/nfs/dir.rs
- src/nfs/helper/dir_helper.rs
- src/nfs/helper/file_helper.rs
- src/nfs/mod.rs
* Make create, shallow_copy, and deep_copy functions private in
dir_helper.
* Move move_dir function from FFI to NFS.
* Fix keys generation for private dirs in NFS.
* Refactor tests code in FFI
> fix/nfs: make dir_helper::create private (MAID-1624)

- src/core/structured_data/mod.rs
- src/core/structured_data/unversioned.rs
- src/dns/config.rs
- src/dns/operations.rs
- src/ffi/dns/file.rs
- src/ffi/dns/long_name.rs
- src/ffi/dns/service.rs
- src/ffi/errors.rs
- src/ffi/launcher_config.rs
- src/ffi/logging.rs
- src/ffi/low_level_api/cipher_opt.rs
- src/ffi/low_level_api/data_id.rs
- src/ffi/low_level_api/immut_data.rs
- src/ffi/low_level_api/misc.rs
- src/ffi/low_level_api/mod.rs
- src/ffi/low_level_api/struct_data.rs
- src/ffi/low_level_api/struct_data/mod.rs
- src/ffi/low_level_api/struct_data/tests.rs
- src/ffi/nfs/file.rs
- src/ffi/nfs/file_writing.rs
- src/ffi/object_cache.rs
- src/ffi/session.rs
- src/ffi/test_utils.rs
- src/nfs/dir.rs
- src/nfs/file.rs
- src/nfs/helper/file_helper.rs
- src/nfs/helper/writer.rs
* Implements StructData in low level API (from PR #372)
* Integrates latest changes in `low_level_api::misc` from the master branch (MAID-1666).
* Implements versioned files API in FFI (MAID-1626).
> Low level API for StructData

- src/core/client/mod.rs
- src/ffi/app.rs
- src/ffi/callback.rs
- src/ffi/dir_details.rs
- src/ffi/dns/file.rs
- src/ffi/dns/long_name.rs
- src/ffi/dns/service.rs
- src/ffi/helper.rs
- src/ffi/logging.rs
- src/ffi/low_level_api/appendable_data.rs
- src/ffi/low_level_api/cipher_opt.rs
- src/ffi/low_level_api/data_id.rs
- src/ffi/low_level_api/immut_data.rs
- src/ffi/low_level_api/misc.rs
- src/ffi/low_level_api/struct_data/mod.rs
- src/ffi/macros.rs
- src/ffi/mod.rs
- src/ffi/nfs/dir.rs
- src/ffi/nfs/file.rs
- src/ffi/nfs/file_writing.rs
- src/ffi/session.rs
- use  `catch_unwind_cb` everywhere where appropriate
- make `catch_unwind_cb` more ergonomic
- introduce `try_cb` macro (like `try`, but calls the callback on error)
- fix order of callback arguments (user data first, error code second) in few odd places
- remove `ffi_try` and `ffi_try_ptr` macros (not needed anymore)
> Ffi refactor

- Cargo.toml
- examples/email.rs
- examples/email_stress_test.rs
- src/ffi/app.rs
- src/ffi/callback.rs
- src/ffi/dns/file.rs
- src/ffi/dns/long_name.rs
- src/ffi/dns/service.rs
- src/ffi/helper.rs
- src/ffi/logging.rs
- src/ffi/low_level_api/appendable_data.rs
- src/ffi/low_level_api/cipher_opt.rs
- src/ffi/low_level_api/data_id.rs
- src/ffi/low_level_api/immut_data.rs
- src/ffi/low_level_api/misc.rs
- src/ffi/low_level_api/struct_data/mod.rs
- src/ffi/mod.rs
- src/ffi/nfs/dir.rs
- src/ffi/nfs/file.rs
- src/ffi/nfs/file_writing.rs
- src/ffi/session.rs
- src/ffi/string_list.rs
- src/ffi/test_utils.rs
- src/lib.rs
- tests/email_stress.rs
libc dependency can be replaced with `std::os::raw::*`
> chore/deps: remove redundant libc dependency

- src/ffi/dir_details.rs
- src/ffi/file_details.rs
Made possible by the removal of drop flags in 1.13.
> refactor/ffi: impl Drop for FileDetails/DirDetails

- README.md
As explained in [this topic](https://safenetforum.org/t/please-update-your-forum-bookmark-to-safenetforum-org/11358), the previous URL is no longer working. The new URL of the SAFE Network Forum is [safenetforum.org](https://safenetforum.org/).
I also added a link to the new [Dev Forum](https://forum.safedev.org/).
> add link to SAFE Dev Forum and fix link to SAFE Network Forum

- Cargo.toml
- src/ipc/mod.rs
New version of rustc-serialise was released with builtin impl for
Result.
> refactor/ipc: remove manual impl of RustCEncodable for IpcResp

- src/app/ffi/ipc.rs
- src/app/ffi/nfs.rs
- src/app/mod.rs
- src/app/test_util.rs
- src/authenticator/ffi/mod.rs
- src/authenticator/ipc.rs
- src/authenticator/mod.rs
- src/ipc/mod.rs
- src/ipc/req/ffi.rs
- src/ipc/req/mod.rs
Also contains changes to data types stored in the access container (replaced ContainerPermissions with BTreeSet<Permission>)
> feat/authenticator: add API to get all registered apps

- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/non_networking_test_framework/storage.rs
Routing has remove requirement of min section size in client interface - so removing that in mock and in production code here too.
Rustfmt changes.
> refactor/integration: integrate with latest routing master

- safe_app/src/ffi/cipher_opt.rs
- safe_app/src/ffi/immutable_data.rs
The code was wrongly trying to extract encryption keys even if the data (cipher-opt variant) was plaintext. That should only happen if the type is not plain text else all fetches by unregistered apps will fail even if the data was plaintext because unreg-clients don't have enc-keys.
> fix/unreg-client: allow unreg client to fetch immut-data

- ffi_utils/src/base64.rs
`=`-padding is not URL-safe; our primary use case for `ffi_utils::base64_encode` ....
> MAID-1995: Disable padding

- safe_app/src/ffi/mutable_data/helper.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/permissions.rs
Special value 0 for 'User::Anyone' wasn't handled correctly in several permission sets functions
> fix/ffi: fix users handling in permission sets

- safe_core/src/nfs/ffi.rs
- safe_core/src/nfs/file.rs
chrono::DateTime<UTC> is not suitable for FFI - use timestamps with second and nanosecond values instead
> fix/ffi: use timestamps instead of structs for date/time

- ffi_utils/src/lib.rs
- ffi_utils/src/vec.rs
- safe_app/src/ffi/access_container.rs
- safe_app/src/ffi/mdata_info.rs
- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_authenticator/src/access_container.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests.rs
Get rid of `AlreadyAuthorised` error, fix app reauthentication after revoke, fix unsafe pointers returned by FFI functions
> Multiple fixes for an incorrect FFI behaviour

- safe_app/Cargo.toml
- safe_app/src/ffi/mdata_info.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_core/Cargo.toml
To make the API more consistent, we don't encrypt values and keys in MutableData actions automatically now - a user has to do this manually. The same applies to mdata_get_value function, which doens't decrypt values from private MData anymore. This commit also adds tests for MutableData FFI APIs which were missing.
> refactor/ffi: remove automatic encryption of MData actions

- ffi_utils/src/callback.rs
- ffi_utils/src/catch_unwind.rs
- ffi_utils/src/lib.rs
- ffi_utils/src/macros.rs
- ffi_utils/src/test_utils.rs
- safe_app/src/errors.rs
- safe_app/src/ffi/access_container.rs
- safe_app/src/ffi/cipher_opt.rs
- safe_app/src/ffi/crypto.rs
- safe_app/src/ffi/helper.rs
- safe_app/src/ffi/immutable_data.rs
- safe_app/src/ffi/ipc.rs
- safe_app/src/ffi/mdata_info.rs
- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/entry_actions.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/permissions.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_app/src/ffi/nfs.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/ffi/public_id.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/tests.rs
Now, instead of passing just an error code (which isn't useful in case of an error types that carry extra info,
like e.g. `AppError::Unexpected` and others), we pass an error description along with it. All callbacks should take the `FfiResult` argument in place of `i32` error code.
> refactor/ffi: use new convention for errors in callbacks

- safe_app/src/ffi/mod.rs
- safe_app/src/lib.rs
- safe_core/examples/gen_invites.rs
- safe_core/src/client/mod.rs
This fixes TODO items in both safe_core and safe_app.
Bootstrap config should be provided in the same format as it is provided in the AuthGranted struct.
> fix/safe_core: support providing bootstrap configs for unregistered clients

- safe_app/src/ffi/ipc.rs
- safe_app/src/ffi/mod.rs
- safe_authenticator/src/ffi/mod.rs
Previously account creation & login functions in both safe_app and safe_authenticator didn't follow the standard convention of returning FfiResult in a callback.
> refactor/all: follow callback result conventions

- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/public_id.rs
- safe_authenticator/src/tests.rs
- safe_core/src/ipc/resp/mod.rs
1. The test for this case was missing.
2. The fact that MData entries aren't removed for now but blanked out wasn't taken into account.
3. There was a missing decryption step before trying to deserialise an app-specific container.
> fix/authenticator: fix reauthorisation of revoked apps

- .travis.yml
- appveyor.yml
- safe_app/src/ffi/mdata_info.rs
- safe_app/src/ffi/mod.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/tests.rs
- safe_core/src/client/mock/mod.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/client/routing_event_loop.rs
+ Fix incorrect network events handling (expect `Event::Terminate` instead of `Event::RestartRequired`).
+ Add more tests for network event callbacks from the FFI point of view.
+ Improve functions signatures for `create_acc`, `login` in safe_authenticator and for `app_registered` and `app_unregistered` in safe_app.
> Fix incorrect network events handling

- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/vault.rs
Previously mock-vault didn't synchronise with the file system on reads. This approach works if it's confined
to a single process, but if e.g. safe_authenticator and safe_app are two different processes, then weird bugs can occur, when safe_app could have a state in memory that is inconsistent with stored MockVault data.
> fix/mock-vault: fix read synchronisation

- ffi_utils/src/catch_unwind.rs
- ffi_utils/src/lib.rs
- ffi_utils/src/test_utils.rs
- safe_app/src/ffi/ipc.rs
- safe_app/src/ffi/mod.rs
- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mod.rs
Expose an API for IPC to get config without needing to sign in. Now safe_authenticator adds new functions that don't require to provide authenticator handle for getting bootstrap config for unregistered apps.
> refactor/safe-authenticator: improve API to get network config

- safe_app/src/ffi/cipher_opt.rs
- safe_app/src/ffi/helper.rs
- safe_app/src/ffi/mod.rs
- safe_app/src/lib.rs
- safe_app/src/object_cache.rs
- safe_app/src/test_utils.rs
- safe_authenticator/src/access_container.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/public_id.rs
- safe_authenticator/src/test_utils.rs
- safe_core/examples/gen_invites.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mod.rs
- safe_core/src/client/routing_event_loop.rs
- safe_core/src/errors.rs
- safe_core/src/event_loop.rs
- safe_core/src/immutable_data.rs
- safe_core/src/nfs/data_map.rs
- safe_core/src/nfs/dir.rs
- safe_core/src/nfs/file_helper.rs
- safe_core/src/nfs/reader.rs
- safe_core/src/nfs/std_dirs.rs
- safe_core/src/nfs/writer.rs
- safe_core/src/self_encryption_storage.rs
- safe_core/src/utils/test_utils.rs
Now when the network connection is failed, we do not reconnect to the network automatically - it should be done by a user. For this purpose several new FFI functions have been added - `app_reconnect` and `auth_reconnect`.
Because of this change we have to store `core_tx` channel with the client. That means that `Client` now has to accept a type parameter for the message context - so all `Client` signatures have been changed to `Client<T>`.
> refactor/all: change network re-connect fns

- safe_app/src/errors.rs
- safe_app/src/ffi/nfs.rs
- safe_app/src/object_cache.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/tests.rs
- safe_core/src/nfs/errors.rs
- safe_core/src/nfs/file_helper.rs
- safe_core/src/nfs/writer.rs
Previously, the NFS API in safe_app didn't use all functions provided by safe_core and had a confusing
interface. This commit applies multiple breaking changes to the API with the purpose of cleaning it up and fixing multiple bugs (e.g. file modification time wasn't updated properly).
> refactor/safe_core: improve NFS implementation

- safe_core/src/client/mock/vault.rs
A number of limits for new accounts has been increased to 1000
> fix/mock-vault: increase mutations limit to conform with actual vaults

- safe_app/README.md
- safe_app/src/ffi/crypto.rs
- safe_app/src/ffi/immutable_data.rs
- safe_app/src/ffi/mdata_info.rs
- safe_app/src/ffi/mutable_data/metadata.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/tests.rs
- safe_core/src/ffi.rs
- safe_core/src/ipc/req/mod.rs
- safe_core/src/ipc/resp/ffi.rs
- safe_core/src/ipc/resp/mod.rs
1. Created type definitions for FFI arrays and refactored out common ffi types.
2. Created a new API to fetch a list of apps that have access to an arbitrary MD.
> New API in Authenticator to fetch a list of apps accessing arbitrary MD (MAID-2247)

- Cargo.lock
- safe_core/Cargo.toml
- safe_core/src/client/mock/vault.rs
- safe_core/src/lib.rs
`maidsafe_utilities` introduced a new change that turned out to be a regression: in some cases when a deserialised struct is serialised again, the binary representation might be different.
This is now an error in the serialisation functions in `maidsafe_utilities` because it can prevent tampering of serialised messages. At the same time, this error prevented mock-vault from loading successfully in some edge cases. This commit fixes that by temporarily using `bincode` to deserialise the mock-vault data, and now we make sure to output error messages, if there are any (previously they were silenced).
> fix/mock-vault: fix mock vault deserialisation (MAID-2262)

- Cargo.lock
- safe_core/Cargo.toml
- safe_core/src/client/mock/vault.rs
- safe_core/src/lib.rs
When mock-vault saved the changes to disk it didn't truncate the previous file contents. This could cause different hard-to-catch bugs, including the one reported in MAID-2262.
> fix/mock-vault: fix mock vault write mode

- safe_app/src/ffi/nfs.rs
NodeFFI dereferences all non-null pointers even if the user does not intend to. Rust returns non-null ptr for empty vectors (0x01) due to it memory allocator. NodeFFI derefences this, so to prevent this use as_safe_ptr which coerces to (0x0).
> fix/ffi: change to using as_safe_ptr

- safe_app/src/ffi/crypto.rs
- safe_app/src/ffi/ipc.rs
- safe_app/src/ffi/mdata_info.rs
- safe_app/src/lib.rs
- safe_app/src/object_cache.rs
- safe_core/src/client/account.rs
- safe_core/src/client/mdata_info.rs
- safe_core/src/client/mod.rs
- safe_core/src/crypto.rs
- safe_core/src/immutable_data.rs
- safe_core/src/ipc/resp/mod.rs
- safe_core/src/lib.rs
- safe_core/src/nfs/data_map.rs
- safe_core/src/nfs/file_helper.rs
- safe_core/src/nfs/reader.rs
- safe_core/src/nfs/writer.rs
- safe_core/src/utils/mod.rs
Rebase of #572 on the latest master branch.
Replace all secret keys (`rust_sodium::crypto::box_::SecretKey`, `rust_sodium::crypto::secretbox::Key` and `rust_sodium::crypto::sign::SecretKey`) with drop-in equivalents that implement "secure cloning" - they don't actually clone the underlying data but instead implicitly share it. This is supposed to prevent some attack vectors.
> MAID-1612: Do not clone secret keys

- ffi_utils/src/test_utils.rs
- safe_app/src/ffi/mod.rs
- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_app/src/ffi/tests/mod.rs
- safe_app/src/lib.rs
- safe_app/src/test_utils.rs
- safe_app/src/tests/mod.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests/mod.rs
- safe_authenticator/src/tests/revocation.rs
- safe_authenticator/src/tests/share_mdata.rs
- safe_authenticator/src/tests/utils.rs
Instead of a network-events callback, have a simpler callback whose call alone indicates that a disconnect occurred.
> refactor/app: optimise the network events callback

- safe_app/src/tests/mod.rs
- safe_authenticator/src/app_auth.rs
- safe_authenticator/src/tests/mod.rs
- app re-authorisation should only use PUTs if it is creating the app container for the first time.
- this PR fixes buggy logic that was unnecessarily updating app containers on every authorisation.
> fix/auth: fix app re-authorisation using 2 PUTs

- Cargo.lock
- ffi_utils/Cargo.toml
It is required because newer version of clap depend on crates that are incompatible with Rust 1.19 (which is currently the only version that we support). This fix needs to be reverted as soon as we'll upgrade to the newer Rust compiler.
> fix/safe_app: fix clap dependency

- appveyor.yml
This hardcoded toolchain version is easy to overlook and it can prevent the CI from deploying the release artifacts. It also serves no purpose because the correct toolchain version (stable) is already selected by filtering out by the branch in the deploy script. Thus it's been removed.
> chore/ci: remove fixed Rust version from deploy script

- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_authenticator/src/ffi/ipc.rs
- safe_core/src/ffi/ipc/resp.rs
- safe_core/src/ipc/resp.rs
- safe_core/src/utils/test_utils/mod.rs
API changes:
- `mdata_list_entries` => `mdata_entries`
- `mdata_entries_for_each` => `mdata_list_entries`
-  new`MDataEntry` struct, returned by `mdata_list_entries`
>  refactor/ffi: refactor `mdata_entries_for_each` to `mdata_list_entries`

- .travis.yml
- scripts/build-all
- scripts/build-binary
- scripts/build-ffi-utils
- scripts/build-mock
- scripts/build-real
- scripts/check-all
- scripts/check-debug-all
- scripts/check-debug-ffi-utils
- scripts/check-debug-mock
- scripts/check-debug-real
- scripts/check-ffi-utils
- scripts/check-mock
- scripts/check-real
- scripts/clippy-all
- scripts/clippy-ffi-utils
- scripts/clippy-mock
- scripts/clippy-real
- scripts/rustfmt
- scripts/stable
- scripts/test-all
- scripts/test-binary
- scripts/test-ffi-utils
- scripts/test-mock
+ fix cache issues by splitting up jobs and using build stages
+ build and cache the binary compatibility test whenever we push to master
+ run clippy with the `--release` flag
The final configuration uses four build stages. We can't get it down any lower without running into timeouts on an empty cache. With four build stages we do not have timeouts and we can avoid restarting CI, saving time overall.
> [MAID-2650] address long Travis build times

- safe_app/resources/SafeApp.AppBindings/AppBindings.Manual.cs
- safe_authenticator/resources/SafeAuth.AuthBindings/AuthBindings.Manual.cs
linter fix : make delegates readonly in manual resource files.
> MAID-2894 - make callback delegates readonly in csharp  manual bindings

- .travis.yml
- appveyor.yml
Add a no-op `script` step to prevent Travis's default script from running.
Do not use `script: skip` so that `before_script` still runs.
> Version change: safe_app to 0.8.0; safe_authenticator to 0.8.0; safe_core to 0.31.0;

- Cargo.lock
- safe_app/Cargo.toml
- safe_app/build.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/build.rs
Because `ffi_utils` was split out into its own repository in PR #665 the `bindgen` build was broken as it depended on having it in the same repo as the rest of Client Libs. This PR fixes it by explicitly including the `FfiResult` struct as inline code (as we don't use anything else from `ffi_utils`).
> Fix bindgen builds [MAID-3142]

- appveyor.yml
- safe_core/src/client/mock/vault.rs
We didn't reposition the file cursor after truncating it which lead to DeserialiseExtraBytes error on a mock vault read attempt. Fixes #681.
Also incorporates changes from #682
> Fix mock vault corruption

- Cargo.lock
- safe_app/Cargo.toml
- safe_app_jni/Cargo.toml
- safe_app_jni/src/lib.rs
- safe_authenticator/Cargo.toml
- safe_authenticator_jni/Cargo.toml
- safe_authenticator_jni/src/lib.rs
- safe_core/Cargo.toml
- tests/Cargo.toml
By default Android JNI derives the class loader from the last Java class available in the call stack. This fails in case if we call from non-Java context (as we do when we call Java callbacks from the event loop thread
in SAFE Client Libs). This PR fixes this by caching the class loader during the library load and using it afterwards to look up Java classes.
Also, this PR uses fixed & updated `ffi_utils` and `safe_bindgen` to generate more robust JNI code and also use proper JNI threads detachment (using [`EnvGuard`](https://github.com/maidsafe/ffi_utils/blob/f7567e63f7258b18268b889af542a2d65274bb1c/src/java.rs#L21-L32) from `ffi_utils`).
> Fixes for Java/JNI bugs [MAID-2659]

- .travis.yml
Without checking for the version-based commit message, the package that
gets produced will always have a version number in it. This is the same
condition that gets checked during the `before_script` step, but it's
easier to just check the same condition again, as it's hard to share
information between steps. We don't need the 2nd condition that appears
in `before_script` because the build will have already failed if that's
wrong.
> chore/ci: conditionally create package

- .travis.yml
- scripts/build-binary
The scripts/build-binary script was grabbing the oldest build instead of
the most recent. This commit fixes that with some command-line magic to cache
the binary we just built.
> test/binary: fix binary compatibility test

- safe_app/src/ffi/nfs.rs
- safe_core/src/nfs/reader.rs
- safe_core/src/nfs/tests.rs
- safe_core/src/nfs/writer.rs
> test/nfs: add test for concurrent file opening

- README.md
- safe_app/README.md
- safe_authenticator/README.md
- safe_core/README.md
+ Clean up commands in README to consistently use `--release`.
+ Fix some minor markdownlint errors about blank lines.
> doc/readme: more explicitly encourage using the --release flag

- safe_app/src/ffi/crypto.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/permissions.rs
- safe_app/src/tests/mutable_data.rs
- safe_core/src/client/mock/routing.rs
- tests/src/real_network.rs
+ Fix some grammatical issues in FFI docstrings
+ Make docstrings mentioning `USER_ANYONE` more consistent
+ Make use of specific subtypes of `NULL_OBJECT_HANDLE` to eliminate potential type errors
+ Add a test for the case where `USER_ANYONE` is passed into `sign_pub_key_get`
> doc/app: improve docstrings for public functions

- Makefile
- scripts/Jenkinsfile
- scripts/package.rs
Hi Nikita/Marcin,
This extends the Jenkins build for macOS (Stephen informed me that it's officially macOS now and not OSX :)).
It's very simple this time: it just copies what's already there for Linux and Windows. The bulk of the work was in the infrastructure, which is in the safe-build-infrastructure repo.
Cheers,
Chris
> Jenkins Build for macOS

- scripts/package.rs
Hi Nikita/Marcin,
This extends the packaging to produce both a zip and a tar.gz. I haven't added any arguments to control producing either a tar or a zip, assuming it's ok to just produce both. I could add those if you would prefer for it to be more controlled.
Even although this is just a packaging script, I would appreciate if you could advise me on line 384. I need to take the full path of the lib to add to the archive and just grab the filename of it, otherwise in a tar it will add the folders to the archive. I've used path functions in other programming languages, so that part is fine. The issue is the conversion of the path to a string and all the unwrapping. I wasn't sure about that: is there a more concise way to do what I'm trying to do there?
Cheers,
Chris
> Package Artifacts as Tar Archive

- appveyor.yml
- scripts/package.ps1
This setting was never enabled in the packaging script, so I think these
deployments have been broken for a while, as rebuilding has explicitly
been controlled with a switch I introduced some time ago.
This also extends the deployment to look for any .tar.gz files produced.
> chore/ci: perform rebuild for windows deployment

- scripts/Jenkinsfile
Hi Nikita,
Very simple one for a change! :)
For supporting PRs and builds for pushes to branches, I'm moving the SCL setup for Jenkins to use a Multibranch Pipeline project type rather than a single pipeline type. We need a slightly different checkout mechanism for that project type or it won't run at all.
There may be more things related to this over the next couple of weeks, but for now I need this simple change to make it easier to get things running.
Cheers,
Chris
> refactor/build: change clone method

- safe_app/src/ffi/tests/mod.rs
- safe_authenticator/src/apps.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/revocation.rs
- remove logic for application management from the FFI layer and expose them as native Rust API
- refactor their respective FFI functions as wrappers to the native API
- add the `RegisteredApp` native RUST structure and implement a `into_repr_c()` function to convert it to the FFI struct representation
- make revocation functions publicly accessible in the API
closes #771, closes #786
> refactor/safe_authenticator: provide Rust API for application management and revocation

- safe_app/src/ffi/access_container.rs
- safe_app/src/ffi/cipher_opt.rs
- safe_app/src/ffi/crypto.rs
- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/entry_actions.rs
- safe_app/src/ffi/tests/nfs.rs
- safe_app/src/lib.rs
- safe_app/src/test_utils.rs
- safe_app/src/tests/mod.rs
- safe_app/src/tests/mutable_data.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/std_dirs.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests/mod.rs
- safe_authenticator/src/tests/revocation.rs
- safe_authenticator/src/tests/share_mdata.rs
- tests/src/lib.rs
- expose run helper function to execute futures by blocking the thread until the result arrives
- refactor the existing run helper in test_utils to call this function
closes #776
> feat/safe_app: expose run helper

- Cargo.lock
- Makefile
- safe_core/Cargo.toml
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- scripts/Dockerfile.build
- scripts/Jenkinsfile
- Improve mock impl. for MData by introducing a local enum in the mock vault impl.
- Add MsgIdConverter trait
- Add functions to the `Client` trait for other mutable data operations
with relevant tests
> Improvements to mock MutableData implementation

- Cargo.lock
- mock_routing/Cargo.toml
- safe_app/Cargo.toml
- safe_app/src/client.rs
- safe_app/src/tests/coins.rs
- safe_app/src/tests/unpublished_mutable_data.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/apps.rs
- safe_authenticator/src/client.rs
- safe_core/Cargo.toml
- safe_core/src/client/account.rs
- safe_core/src/client/core_client.rs
- safe_core/src/client/mock/mod.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- tests/Cargo.toml
- Adapt to the changes in safe-nd for data type structs and request/response types
- Add `FullId` variant to mock-routing from which the vaults fetch the requester field
- Implement proper approach to signature verification and permissions validation for mutable / immutable data
- Re-enable IData tests
Resolves #849
> Adapt to the API changes in safe-nd

- safe_app/src/client.rs
- safe_app/src/tests/unpublished_mutable_data.rs
- safe_authenticator/src/client.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/ipc/resp.rs
- Use imports instead of mentioning the package in-line
- Use `PublicKey::from` instead of explicitly mentioning `PublicKey::Bls`
- Impl `Into` trait to convert `AppKeys` into `AppFullId`
- Re-use BLS key from `mock_routing::FullId`
- Combine `req_as_app` and `req_as_owner` functions for tests
- Use common signature verification for all requests
> Multiple improvements based on review comments

- safe_core/src/client/mock/mod.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- Implements feature complete AppendOnly Data RPCs
- Implements AppendOnly Data in Mock Vault
- Adds tests for AppendOnly Data RPCs
> feat/adata: implement AppendOnly Data RPCs and support AppendOnly Data in Mock Vault

- scripts/Dockerfile.build
Hi Nikita,
I'm setting up a job in Jenkins to build the container automatically on a merge to `experimental` or `master`, so need the Docker build definition changed to build mock rather than real.
Cheers,
Chris
> Use build-mock in Container Build

- Cargo.lock
- safe_app/src/tests/coins.rs
- safe_core/src/client/mock/account.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- Implement create_coin_balace that creates a new coin balance for a
given address and public key, preloaded with some safecoin from an
existing wallet. If the existing wallet does not use the client's owner
key then the secret key must be specified
- Remove source fields from safecoin transactions, the wallet address is
derived from the Public Id of the client
- Replace the dest parameter in routing::send with a requester field to
send an optional PublicKey in case of arbitrary wallet transactions
- Refactor the handling of wallet transactions in the mock vault to
adapt to the above changes
Resolves #851, #844
> Implement CreateCoinBalance RPC and remove src parameter for safecoin transactions

- safe_core/src/client/mock/mod.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/vault.rs
>  refactor/data: avoid namespace collision and type erasure in DataId 

- scripts/Dockerfile.build
This synchronises the IDs with the IDs of the `jenkins` user on the build slave. This should hopefully reduce the Linux build time quite significantly, because it avoids having to change permissions for thousands of files (this is a classic problem with Docker - details [here](https://boxboat.com/2017/07/25/fixuid-change-docker-container-uid-gid/) if you're interested). The external disks used by machines on AWS are quite slow, so changing all the permissions can take 5 - 10 minutes sometimes.
Once this is merged I can regenerate the slave with the updated container.
Cheers,
Chris
> Update Container IDs

- safe_core/src/client/mock/mod.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- Adapt to the latest changes in safe-nd
- Handle RPCs for login packet operations
- Add `create_account` and `get_account` public API to establish new routing instances and perform the required operations
closes #858
> Implement login packet operations

- safe_app/src/tests/coins.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
Users with a wallet and without an account should be able to perform coin operations. The functions added will allow coin operations to be performed, provided the secret key of the wallet is provided.
> Add functions for safecoin operations without a client instance

- Cargo.lock
- safe_app/src/tests/unpublished_mutable_data.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
Resolves #885 and #889 
- Fixes new mutable data safe_app tests
- Adds tests for validation of owners before PUTs
- Renames mock vault file name to 'SCL-Mock'
> fix/all: fix validation of Owners before PUT for all data types and rename mock vault file

- Makefile
- scripts/Jenkinsfile
Hi Nikita/Lionel/Marcin,
In the interest of saving time, this combines the build and test into one stage. There wasn't really any need for an explicit build stage.
This also introduces a 'cache' for the Windows build. Due to Jenkins creating a new workspace for every PR and the way Cargo is designed, this meant every PR opened would force a Windows build from scratch, which takes about 25 minutes. If there is no target directory in the workspace (the first time building the PR), the build now retrieves a pre-built target directory that is based on a build of the experimental branch at the last merge.
Finally, at the end of the process, on a merge to experimental, it will trigger a build to regenerate the cache and also the Docker container. …
> Combine Build and Test Stages

- safe_app/src/client.rs
- safe_app/src/tests/mod.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- tests/src/lib.rs
- Create a random keypair for every unregistered session and init routing using a ClientFullId generated from those keys
- Add tests for unregistered access to published AData
Resolves #899, #900
> Allow GET requests to be sent by unregistered clients

- safe_app/src/tests/mutable_data.rs
- safe_app/src/tests/unpublished_mutable_data.rs
- safe_authenticator/src/app_auth.rs
- safe_authenticator/src/client.rs
- safe_authenticator/src/revocation.rs
- safe_authenticator/src/tests/mod.rs
- safe_authenticator/src/tests/revocation.rs
- safe_core/src/client/core_client.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/client/recovery.rs
Resolves #896 and #897 
- Introduces a new trait implementing functions which are not supposed to be called by AppClients
- Adapts safe_authenticator to the new impl
- Fixes tests for auth keys
> fix/all: disable AppClients from accessing Auth Keys

- safe_app/src/ffi/nfs.rs
- safe_app/src/ffi/tests/nfs.rs
First contribution. I think I crossed all t's and dotted all i's.
> chore/ffi: allow file_open to accept null file arg #783

- Cargo.lock
- safe_app/Cargo.toml
- safe_app/src/client.rs
- safe_app/src/lib.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/client.rs
- safe_authenticator/src/lib.rs
- safe_core/Cargo.toml
- safe_core/src/client/core_client.rs
- safe_core/src/client/mod.rs
- safe_core/src/event_loop.rs
- safe_core/src/utils/test_utils/mod.rs
`tokio_core` has been deprecated for a while, causing some troubles. We had to fix the dependency version at `=0.1.8`. This PR updates `tokio_core` to latest `tokio`.
Closes #923
> Upgrade the deprecated tokio_core dependency

- Cargo.lock
- mock_routing/src/lib.rs
- safe_app/src/tests/unpublished_mutable_data.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/errors.rs
- safe_core/src/nfs/errors.rs
+ Do not return early errors from `process_request`, encapsulate them in the
proper response variant instead
+ Do not unwrap result of `process_request` in `send`
+ Add missing checks for mismatch between requested data address and received
data kind
+ Do some refactoring and simplication of `process_request`
Closes #910
> fix/mock: refactor vault::process_request

- safe_authenticator/src/tests/revocation.rs
- safe_core/src/client/mock/vault.rs
>  fix/vault: verify if the app is still authorised when reading data 

- Cargo.lock
- safe_core/Cargo.toml
- safe_core/src/client/mock/tests.rs
- safe_core/src/config_handler.rs
- safe_core/src/connection_manager.rs
- safe_core/src/errors.rs
Read the quic-p2p config from file if it exists in the same way as is done in `safe_vault`.
Resolves #951
> Read quic-p2p config from file

- Makefile
- scripts/Jenkinsfile
- scripts/build-with-container
We had been using the generic slave for this project, but we need to
switch it over to a project specific slave. This will then be rebuilt
with Rust 1.37.
We also remove the container being versioned along with the application.
We don't really need that for a build container and we discovered from
another project that this system doesn't work anyway. When you try to
upgrade to a new version there is no container for that version, so it
doesn't work with the version change commit system. We may change the
tag later on from 'build' to perhaps the name of the branch, but this
works for now.
> chore/ci: use project specific slave

- Makefile
- scripts/Dockerfile.build
Somehow this ended up with the . missing at the end, which is required for a docker build command.
> Fix Build Container

- Cargo.lock
- safe_app/src/client.rs
- safe_app/src/tests/mod.rs
- safe_authenticator/src/client.rs
- safe_core/src/client/account.rs
- safe_core/src/client/core_client.rs
- safe_core/src/client/id.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
Also implement `compose_message` as a trait method on `Client`
Fixes #995
Fixes #994
Fixes #958
> refactor/client: make `Client::full_id` return `SafeKey`

- Makefile
This directory causes the 'cargo package' command to fail.
> fix/ci: remove deploy directory before publish

- .travis.yml
- safe_authenticator/src/tests/serialisation.rs
- scripts/check-all
- scripts/clippy-all
Also, it looks like [this](https://github.com/rust-lang/rust-clippy/issues/2831) was fixed some time back! A report of the bug and its fix can be found [here](https://phansch.net/2018/10/10/fixing-a-clippy-crash/).
> chore/ci: reenable real builds in Travis

- Makefile
- scripts/Jenkinsfile
The standard libraries for Groovy use the Java camelCase style rather than the Python style, so I want these to be consistent with one another and I've started using the Java style for all the other repos. There are also some other minor things like consistently using the same type of quotes for string literals, rather than having an arbitrary mix of single and double.
I wanted to do this in a separate commit and PR so that the diffs on the next PR don't contain this stuff.
> style/ci: change style from python to java

- Makefile
- scripts/Dockerfile.android.armv7.build
- scripts/Dockerfile.android.x86_64.build
- scripts/Jenkinsfile
- scripts/build-android-cache
- scripts/build-with-container
- scripts/get-release-description
- scripts/package-runner-container
- scripts/package.rs
- scripts/retrieve-build-artifacts
Hi Lionel/Ravinder,
This enables builds for Android and iOS, both mock and real versions. They are all built in parallel during the first stage. There's a 2nd stage that combines the 2 iOS libraries into the universal library. The release process has also been extended to include these.
You can see an example release [here](https://github.com/jacderida/safe_client_libs/releases/tag/0.10.1) on my fork. [This](https://jenkins.maidsafe.net/blue/organizations/jenkins/pipeline-safe_client_libs/detail/PR-1037/26/pipeline/343/) was the build that produced that release.
You can see an example of a non-versioned deploy build [here](https://jenkins.maidsafe.net/blue/organizations/jenkins/pipeline-safe_client_libs/detail/PR-1037/23/pipeline/343/). Here are the artifacts uploaded to S3:
``` …
```
> Mobile Build and Release

- .travis.yml
- safe_core/src/ipc/resp.rs
Closes #784
Also re-enables the `app_keys` test.
> test/access_container: add test for `from_mdata_info`

- Cargo.lock
- safe_app/Cargo.toml
- safe_app/src/test_utils.rs
- safe_app/src/tests/append_only_data.rs
- safe_app/src/tests/coins.rs
- safe_app/src/tests/mod.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/test_utils.rs
- safe_core/Cargo.toml
- safe_core/src/client/mock/account.rs
- safe_core/src/client/mock/connection_manager.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/config_handler.rs
- safe_core/src/ffi/ipc/req.rs
- safe_core/src/ipc/req/auth.rs
- tests/Cargo.toml
- tests/src/real_network.rs
> refactor/permissions: refactor permissions handling in Mock Vault to the new granularized AppPermissions

- Cargo.lock
- Makefile
- safe_app/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_core/Cargo.toml
- scripts/Jenkinsfile
- scripts/package-runner-container
- scripts/package.rs
- scripts/publish
- tests/Cargo.toml
This implements:
* Publishing in its own stage, in a sequential manner.
* For a version change build, each component in the workspace is tagged, deployed and published separately.
* A nightly build that will run at 2AM:
- Does a 'dry run' publish
- Deploys all components to S3 in the form `safe_app-nightly-<target triple>.tar.gz`
It felt more correct for publishing to be in its own stage because the publish should only occur if the deployment has been completely successful.
[This](https://jenkins.maidsafe.net/blue/organizations/jenkins/pipeline-safe_client_libs/detail/PR-1038/11/pipeline/) build demonstrates a successful deploy and publish.
You can [see](https://github.com/maidsafe/safe_client_libs/tags) the individual component tags for these test publish runs. I'll delete these once …
> Tagging, Publishing and Nightly Builds

- .travis.yml
- appveyor.yml
- safe_app/examples/client_stress_test.rs
- safe_app/examples/self_authentication.rs
- safe_app/src/lib.rs
- safe_authenticator/src/apps.rs
- safe_authenticator/src/client.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests/mod.rs
- safe_core/src/ipc/req/mod.rs
- safe_core/src/ipc/resp.rs
- safe_core/src/lib.rs
- scripts/clippy-all
- tests/src/lib.rs
- tests/src/real_network.rs
We've already done this in `safe_vault`, now trying it here. This change was
prompted by the new `clippy::missing_safety_doc` lint in 1.39.0 breaking our
compiles.
See https://hackmd.io/8odS50_AQV6U1wCHBfbeuw for further motivation.
- Removed all `forbid` items: most are already `deny` by the compiler, not clear
what explicitly forbidding them gives us.
- `unsafe_code` stayed `deny`, other `deny` items removed as they are all `warn`
and will be caught by CI. The `bad_style` lint was deprecated in favor of
`nonstandard_style`, which is also `warn`.
- Existing `warn` items mostly unchanged, except that a couple were added. These
are all `allow` by the compiler, but useful to get warnings about.
- Removed all `allow` items: they are already `allow` by the compiler.
Also explicitly allowed …
> chore/lints: remove explicitly-listed non-warn lints

- Cargo.lock
- safe_app/Cargo.toml
- safe_app/src/errors.rs
- safe_app/src/ffi/logging.rs
- safe_app/src/ffi/mod.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/client.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/ffi/logging.rs
- safe_authenticator/src/ffi/mod.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/config_handler.rs
- tests/src/real_network.rs
- When running the custom_config_dir the non-mock tests break since the
config file is read from the wrong location. Feature-gate that test
behind mock-network
- In the real vault, for `CreateLoginPacketFor` a balance is first
created and then the login packet is inserted at the specified location.
Make the mock vault consistent with this.
> Fix non-mock tests and inconsistency with real vault

- .github/workflows/master.yml
- .github/workflows/pr.yml
- Makefile
- scripts/Dockerfile.android.armv7.build
- scripts/Dockerfile.android.x86_64.build
- scripts/build-android-cache
- scripts/build-container.sh
- scripts/get-release-description
- scripts/package-runner
- scripts/package.rs
Uses GitHub Actions for the build and release process, though at this point, it doesn't contain any builds for macOS, due to an issue with rust_sodium building on Catalina. The iOS stuff is in here, but it's currently commented out. When the rust_sodium problem is resolved, macOS-latest can be added the the appropriate strategy matrix and the job for building on iOS can be uncommented. After that you'll need to add a job for building the universal iOS library, but you can copy the `safe-api` Actions implementation for that.
The strategy matrix is utilised to reduce as much duplication as possible.
There is a full example build [here](https://github.com/jacderida/safe_client_libs/commit/44c4790158389f8e1b1e5f964332f6f5bbc02b98/checks?check_suite_id=316492320). There is a problem here with …
> chore/ci: use actions for build and release

- .github/workflows/master.yml
The description string is a small yaml document with multiple lines, but set-output truncates anything after the first line. The Actions developers advised fixing it the way it's been done here. I tested this
on safe-api and it works.
Here is the support issue thread:
https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/td-p/37870
> chore/ci: re-enable description for release

- Makefile
- scripts/Jenkinsfile
- scripts/package-runner-container
- scripts/retrieve-build-artifacts
We still don't have macOS builds running in Actions, so we're keeping Jenkins for this for now.
There is a condition in the Makefile target for packaging that checks if we're running on Jenkins, because on there we need to run the packaging process in a container. This can be removed when Jenkins is decommissioned.
> chore/ci: strip jenkins down to macOS

- .github/workflows/master.yml
- Cargo.lock
- safe_app/Cargo.toml
- safe_app/build.rs
- safe_app/src/cipher_opt.rs
- safe_app/src/ffi/ipc.rs
- safe_app/src/ffi/mdata_info.rs
- safe_authenticator/build.rs
- safe_authenticator/src/access_container.rs
- safe_authenticator/src/tests/utils.rs
- safe_core/Cargo.toml
- safe_core/src/client/account.rs
- safe_core/src/client/mdata_info.rs
- safe_core/src/crypto.rs
- safe_core/src/ffi/arrays.rs
- safe_core/src/ipc/resp.rs
- safe_core/src/nfs/tests.rs
- safe_core/src/utils/mod.rs
- Replace the use of symmetric encryption methods from rust-sodium with
miscreant.
- Use pbkdf2 for key generation
- This PR also updates the deploy github action to make the deployed artifacts publicly readable.
> Replace rust-sodium functions for symmetric encryption and key generation

- Cargo.lock
- safe_app/CHANGELOG.md
- safe_app/Cargo.toml
- safe_app_jni/Cargo.toml
- safe_authenticator/CHANGELOG.md
- safe_authenticator/Cargo.toml
- safe_authenticator_jni/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- tests/Cargo.toml
- New versions of safe_core, safe_authenticator and safe_app were
manually released by checking out to commit 26add71
- Update version number and changelog for the above mentioned crates.
- Note that the commit does not follow the standard for version change commits since we don't want the publish github action to be triggered.
> Update version number and changelog

- .github/workflows/master.yml
> chore/ci: add missing macOS build job

- .github/workflows/master.yml
- .travis.yml
- appveyor.yml
- safe_core/src/client/mod.rs
- scripts/package-runner
The last version-commit workflow in master has failed. This PR should fix those issues.
These changes have been tested on my fork [here](https://github.com/m-cat/safe_client_libs/commit/ae2e949b5dd57e00e5e9f2879a296f95c2752e65/checks?check_suite_id=351959029).
It produced [this release](https://github.com/m-cat/safe_client_libs/releases/tag/safe_core-0.37.1-safe_app-0.12.0).
> chore/ci: add missing iOS builds to GHA deploy + fix tags

- safe_core/src/client/mock/mod.rs
- safe_core/src/client/mock/tests.rs
@m-cat this PR is a work in progress to re-enable the tests in the `safe_core::client::mock`.
I have refactored the helper functions used for the tests and re-enabled a single test. Let me know what you think about this approach. If it's okay, then I can proceed with refactoring the other tests as well using the same pattern. Thanks!
EDIT: PR is now ready for review
> Enable tests in safe_core::client::mock

- safe_core/src/client/mock/connection_manager.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
Re-enables 2nd half of the mock vault tests in safe_core.
Rebased on: https://github.com/maidsafe/safe_client_libs/pull/1106
> Enable tests in safe_core::client::mock - Part 2

- .github/workflows/master.yml
- .github/workflows/pr.yml
This PR enables caching in GitHub Actions.
I'm happy to report that, while builds are slightly slower if there is no matching cache, they are significantly faster when the cache is available.
[Control build without cache:](https://github.com/m-cat/safe_client_libs/runs/347511290)
|Ubuntu|Windows|macOS|iOS aarch64|iOS x86_64|
|---|---|---|---|---|
|780s|1219s|529s|569s|568s|
[First build with caching (no cache available):](https://github.com/m-cat/safe_client_libs/runs/347594633)
|Ubuntu|Windows|macOS|iOS aarch64|iOS x86_64|
|---|---|---|---|---|
|913s|1265s|576s|605s|619s|
|117%|104%|109%|106%|109%|
[Second build with caching (cache available):](https://github.com/m-cat/safe_client_libs/runs/347647058)
|Ubuntu|Windows|macOS|iOS aarch64|iOS x86_64|
|---|---|---|---|---| …
> chore/ci: add caching to GHA

- safe_app/src/cipher_opt.rs
- safe_app/src/client.rs
- safe_app/src/errors.rs
- safe_app/src/ffi/crypto.rs
- safe_app/src/ffi/ipc.rs
- safe_app/src/ffi/logging.rs
- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/entry_actions.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/permissions.rs
- safe_app/src/ffi/nfs.rs
- safe_app/src/lib.rs
- safe_app/src/object_cache.rs
- safe_authenticator/src/apps.rs
- safe_authenticator/src/client.rs
- safe_authenticator/src/config.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/ffi/ipc.rs
- safe_authenticator/src/ffi/logging.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/revocation.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests/mod.rs
- safe_authenticator/src/tests/share_mdata.rs
- safe_core/src/client/account.rs
- safe_core/src/client/core_client.rs
- safe_core/src/ffi/ipc/resp.rs
- safe_core/src/ipc/mod.rs
- safe_core/src/ipc/resp.rs
Fixes `clippy::pedantic` warnings and errors for `safe_authenticator` & `safe_app` module. Leaves out some renaming suggestions as to leave the crux structs unchanged.
Rebased on: #1120
> Pedantic auth&app

- .github/workflows/master.yml
The `aws` command is now available in the GHA virtual environments:
https://stackoverflow.com/questions/59166099/github-action-aws-cli
Fixes #1108
> chore/ci: update deprecated AWS action

- safe_core/src/config_handler.rs
- safe_core/src/connection_manager.rs
- safe_core/src/connection_manager/connection_group.rs
If in the quic-p2p config we supply port as unspecified (`None`), quic-p2p will use the default port which is set to 443, or 0 if 443 is unavailable. While this behaviour almost always results in having random ports for clients on *nix operating systems (since low-number ports are restricted to superusers only), it can result in a situation when both local vault and a client bind to the same port number (443). We observed this behaviour on Windows and the solution is to always use a random port for clients.
> Always use a random port for client QUIC connections

- .github/workflows/master.yml
when the find command was executed on windows it used the "C:/Windows/System32/find" executable instead of the expected *NIX binary. This patch uses the full path to the find binary provided by git bash
Tested [here](https://github.com/lionel1704/gh-actions-demo/commit/5370d9bac18b35ecb1c2c831e6ad59a3bd50be5b/checks?check_suite_id=411931272)
> fix/action: fix error in master workflow

- .github/workflows/generate_dependency_graphs.yml
- scripts/generate_dependency_graphs
The Crate graph displayed in the readme & the wiki is out of date. This PR will add auto update of the graph .png file every night, which the readme & wiki point to.
There will still be a (smaller) manual maintenance aspect after this PR - the command which produces the graph every night explicitly states which crates it should display, so if this updates we will need to update the command in the `generate_dependency_graphs` script. Current command:
`cargo deps --all-deps --include-orphans --subgraph safe_app safe_authenticator safe_authenticator_ffi safe_core --subgraph-name "SAFE Client Libs" --filter safe-nd quic-p2p ffi_utils safe_app safe_authenticator safe_authenticator_ffi safe_bindgen safe_core self_encryption --manifest-path safe_app/Cargo.toml | dot -Tpng -Nfontname=Iosevka …
> feat(ci): auto generate dependency graph via CI

- .github/workflows/auto_merge_prs.yml
- .github/workflows/bump_version.yml
- .github/workflows/commitlint.yml
- .github/workflows/github_release.yml
- .github/workflows/master.yml
- .github/workflows/pr.yml
- .github/workflows/tag_release.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Implement a CD process where any PR merged to master will
automatically trigger a crate publish, a tag, a 'chore(release):'
PR which is auto merged, and a GitHub release.
This PR also adds auto merging for dependabot PRs which pass CI.
This PR also reformats the changelog to match the newly auto-
generated format.
Added `Don't merge` label as merging this will result in a release/publish - crate should be considered stable before we merge.
Closes #1089
> chore(cd): add continuous delivery and auto merge dependabot PRs

- .github/workflows/pr.yml
- Cargo.lock
Removed previously as it seemed to be causing CI failures, but no longer able to replicate this failure - ran PR CI x10 on fork.
> chore(ci): readd cache generation to CI

- .github/workflows/pr.yml
Created as draft as this new `cargo deny` CI check will fail until the following 2 items are addressed:
1. Unwrap is removed from sn_client.
2. [RUSTSEC-2020-0043](https://github.com/maidsafe/sn_client/issues/1266) is addressed (bumped that issue).
> Add cargo deny to CI and `cargo intraconv` updates

- src/utils/mod.rs
derive_secrets is also found in sn_api/src/api/authenticator/mod.rs
> chore(utils): remove unused derive_secrets

- scripts/generate_dependency_graphs
Updated to reflect current sn_client internal maidsafe repository dependencies.
Also added a step to the script to generate a Cargo.lock - since this was recently removed from the repo cargo-deps has not been able to run.
> chore(deps): update ci dependency graph generator script

- src/client/transfer_actor/mod.rs
- src/connection_manager.rs
> fix: transfer listener cleanup should happen only once

- src/config_handler.rs
Ideally the code could've just been:
`config.local_port = Some(0)`
As mentioned in #1431
Now qp2p uses a random port by default so this is no longer needed.
Resolves #1431
> chore(connection): remove code that generated a random port for the client

- Cargo.toml
- src/client/mod.rs
- src/client/register_apis.rs
- src/client/sequence_apis.rs
- src/connection_manager.rs
When SectionInfo::Redirect is called we can re-boostrap instead of connecting to all the provided peers and sending the bootstrap request.
In the testnet for a client redirect was sent 8 times which meant 8 x 7 connections which were eventually just dropped.
> Rebootstrap with SectionInfo::Redirect instead of connecting to all peers

- Cargo.toml
> fix(deps): use released version of qp2p instead of git branch

- src/utils/test_utils/mod.rs
the relative path of the configuration file should be a path instead of a string so that it works on platforms like Windows which uses `\`  for separation. Creating a `Path` before joining it, solves the cross-platform issue.
> chore: fix node configuration information file path

- .github/workflows/pr.yml
- .github/workflows/security_audit.yml
BREAKING CHANGE: This should be bumped with messaging changes
This isn't _actually_ a breaking change, but a bump due to an earlier
commit missing one.
PRs starting with the title `Automated version bump` are auto generated as
part of the CI/CD process and so it is duplicate work running the PR workflow
on them. These changes skip PR CI for them.
This PR also switches the scheduled security audit to only run on the MaidSafe
org repo, not on forks.
> feat(cicd): exclude prs with title 'Automated version bump`

- src/connections/messaging.rs
> fix(messaging): don't discard error responses for Blob Queries
