maidsafe/sn_client

- .travis.yml
Must enable coveralls.io for maidsafe_client repository for coverage results to be published in coveralls.io
> coverage integrated

- src/lib.rs
> Remove allow dead_code

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/maidsafe_client/19)
> Replace weird " character

- src/account.rs
- src/client.rs
- src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/maidsafe_client/20)
> PLS PICK UP fix build by updating

- src/account.rs
- src/client.rs
- src/lib.rs
1, pass compilation : cargo build & cargo test
2, correct process for account creation and login
3, resolved some warnings
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/maidsafe_client/23)
> Updating maidsafe_client

- CHANGELOG.md
- README.md
WIP - TODOs for the sprint updated
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/29)
> ChangeLog and TODOs updated

- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/35)
> Maid-1120-non-networking-test-framework

- README.md
- examples/self_authentication.rs
- src/client/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/36)
> CLI User Interactive SelfAuth example coded.

- src/client/callback_interface.rs
- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
- src/client/response_getter.rs
- src/lib.rs
- src/nfs/helper/directory_helper.rs
- src/nfs/io/network_storage.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/39)
> Thread safe response getter

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/41)
> Update ReadMe Todo.

- src/nfs/directory_info.rs
- src/nfs/directory_listing.rs
- src/nfs/helper/directory_helper.rs
- src/nfs/rest/container.rs
REST API for Container creation and retrieval based on version
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/42)
> Maid 1087 container - create & get API

- README.md
- src/nfs/directory_info.rs
- src/nfs/directory_listing.rs
- src/nfs/rest/container.rs
- src/nfs/rest/container_info.rs
- src/nfs/rest/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/43)
> MAID-1088 List and update container

- examples/self_authentication_with_mock_routing.rs
- src/client/mod.rs
- src/client/user_account.rs
- src/nfs/directory_info.rs
- src/nfs/directory_listing.rs
- src/nfs/file.rs
- src/nfs/helper/directory_helper.rs
- src/nfs/helper/file_helper.rs
- src/nfs/io/network_storage.rs
- src/nfs/io/reader.rs
- src/nfs/io/writer.rs
- src/nfs/metadata.rs
- src/nfs/rest/blob.rs
- src/nfs/rest/container.rs
- src/nfs/utils/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/45)
> Minor Refactor

- README.md
- src/nfs/helper/file_helper.rs
- src/nfs/io/mod.rs
- src/nfs/rest/container.rs
Get version and Delete Container implemented
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/46)
> Maid 1089 delete container

- README.md
- src/nfs/rest/container.rs
Maid 1092 get blob and get blob by version implemented. MAID-1091 - get_blobs() was already implemented.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/48)
> Maid 1092 get blob

- README.md
- src/nfs/directory_listing.rs
- src/nfs/rest/blob.rs
- src/nfs/rest/container.rs
- src/nfs/rest/container_info.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/55)
> Maid 1098 update blob

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/56)
> MAID-1101 done

- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
- src/client/user_account.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/58)
> Updated session packet with root dir created and tested

- src/client/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/64)
> Fixes #63 fix

- README.md
- examples/rest_api.rs
- src/nfs/rest/blob.rs
- src/nfs/rest/container.rs
- src/nfs/rest/container_info.rs
Tests implemented
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/65)
> tests implemented

- examples/rest_api.rs
Formatting version number logic was breaking. Fixed it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/67)
> Fixes #66 REST API Example

- src/client/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/68)
> improvement in branchings

- README.md
pre-requisite libsodium added
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/71)
> Fixes #69 Readme

- examples/rest_api.rs
- examples/self_authentication_with_mock_routing.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/74)
> Fixes #73 - Leading zeroes now allowed in PIN

- examples/rest_api.rs
- examples/self_authentication_with_mock_routing.rs
- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
- src/client/response_getter.rs
- src/client/user_account.rs
- src/lib.rs
- src/nfs/helper/directory_helper.rs
- src/nfs/helper/file_helper.rs
- src/nfs/rest/container.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/76)
> Fixes #75 - tests updated for persistent storage

- maidsafe_client-b676cf89b5b9fc72.bootstrap.cache
- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/82)
> Fixes #81 - Passing bootstrap information to routing as Option::None

- CHANGELOG.md
- Cargo.toml
- README.md
Reverts maidsafe/maidsafe_client#83
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/84)
> Revert "Version change to 0.1.0"

- Cargo.toml
- src/client/mod.rs
- src/nfs/helper/directory_helper.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/85)
> Sodiumoxide and Self-encryption to version "*" and corresponding changes

- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/88)
> Updated links.

- .gitignore
- src/client/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/90)
> Sleep hack to allow bootstrapping

- examples/rest_api.rs
- src/nfs/helper/file_helper.rs
- src/nfs/io/mod.rs
- src/nfs/io/writer.rs
- src/nfs/rest/container.rs
Updating blob content was not re-writing it completely. Fixed the same
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/91)
> Update blob content fix

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/95)
> Todo rust 3

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/rest_api.rs
- src/client/user_account.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/97)
> Version change to 0.1.1

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/rest_api.rs
- src/client/user_account.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/98)
> Bring 0.1 up to date with master

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/99)
> version change to 0.1.2

- .gitignore
Ignore the *.bootstrap.cache files that are automatically created when running the examples.  These are also ignored in the maidsafe_vault branch.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/103)
> Ignore *.bootstrap.cache files.

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/105)
> Todo correction

- src/client/mock_routing_types.rs
- src/lib.rs
- src/structured_data_operations/mod.rs
- src/structured_data_operations/unversioned.rs
- src/structured_data_operations/versioned.rs
- src/utility.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/106)
> MAID-1230 versioned structured data

- src/client/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/107)
> reduce bootstrap delay to check test status

- Cargo.toml
- src/lib.rs
- src/utility/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/113)
> purging maidsafe_types and misc improvements

- src/client/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/114)
> API added for getting the encryption and signing keys

- src/structured_data_operations/unversioned.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/115)
> correcting alignment

- src/errors.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/116)
> Debug trait

- src/utility/test_utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/117)
> test helper macros

- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
- src/client/user_account.rs
- src/macros.rs
- src/utility/mod.rs
- src/utility/test_utils.rs
create eval_option!()
remove unsafe
remove unwrap
update all test_cases
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/118)
> use eval_result!()

- examples/self_authentication.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/119)
> removing unused_must_use attribute

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/self_authentication.rs
- src/id/id_type.rs
- src/id/public_id_type.rs
- src/id/revocation_id_type.rs
- src/lib.rs
- src/macros.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe_client/122)
> Rename repositories from "maidsafe_" to "safe_"

- src/structured_data_operations/mod.rs
Tests approximate_space_for_data and data_can_fit_in_structured_data fixed
> Failing tests fixed

- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
- src/lib.rs
<2> Removing warning due to deprecated lint-check
> <1> Integrating new Routing API

- Cargo.toml
- README.md
- appveyor.yml
- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
- src/client/user_account.rs
- src/errors.rs
- src/lib.rs
<2> Scrypt used instead of PBKDF2 as it is more superior in its purpose
> Fixes #62 - <1> rust-crypto dependency removed

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_client/148)
> Version change to 0.1.4

- src/client/message_queue.rs
- src/client/mod.rs
- src/client/non_networking_test_framework/mod.rs
- src/lib.rs
- src/structured_data_operations/mod.rs
- src/structured_data_operations/versioned.rs
- src/utility/mod.rs
<2> Adding version cache test case
> <1> MAID-1299

- README.md
- src/client/message_queue.rs
- src/client/non_networking_test_framework/mod.rs
- src/id/public_id_type.rs
- src/lib.rs
Replacing PR https://github.com/maidsafe/safe_client/pull/176
> Lint checks

- .travis.yml
- Cargo.toml
- examples/safe_client.rs
- examples/self_authentication.rs
- src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/205)
> Add clippy, update lints and add nightly for travis.

- examples/safe_client.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/204)
> make safe_client example includes the messaging feature

- src/client/mod.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/208)
> Added sleep to Put request temporarily.

- src/self_encryption_storage.rs
- src/structured_data_operations/unversioned.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/210)
> Updates for latest SE. SE and this requires version change.

- src/translated_events.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/213)
> Into trait for events to get them across FFI boundary

- Cargo.toml
- examples/simulate_browser.rs
- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/response_getter.rs
- src/core/errors.rs
- src/core/self_encryption_storage.rs
- src/core/structured_data_operations/mod.rs
- src/core/structured_data_operations/unversioned.rs
- src/core/structured_data_operations/versioned.rs
- src/core/translated_events.rs
- src/dns/dns_operations/mod.rs
- src/lib.rs
- src/nfs/file.rs
- src/nfs/helper/directory_helper.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/217)
> Response handling

- CHANGELOG.md
- Cargo.toml
- examples/safe_client.rs
- examples/self_authentication.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/structured_data_operations/mod.rs
- src/core/structured_data_operations/unversioned.rs
- src/core/utility/test_utils.rs
- src/lib.rs
This PR incorporates https://github.com/maidsafe/safe_core/pull/218, so that one should be merged before this one.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/219)
> Version change to 0.9.0

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/222)
> Version change to 0.10.0

- src/core/client/mod.rs
- src/core/client/user_account.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/221)
> Use gender-neutral pronouns.

- Cargo.toml
- examples/safe_client.rs
- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/response_getter.rs
- src/core/client/user_account.rs
- src/nfs/metadata/file_metadata.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/223)
> Reintegrating messaging

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/224)
> Version change to 0.11.0

- Cargo.toml
- examples/client_stress_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/225)
> Added client_stress_test example.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/228)
> Version change to 0.12.1

- Cargo.toml
- examples/client_stress_test.rs
- examples/safe_client.rs
- examples/self_authentication.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/232)
> Updated dependencies.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/233)
> Version change to 0.13.0

- CHANGELOG.md
- Cargo.toml
- src/core/errors.rs
Affects: Cargo.toml CHANGELOG.md src/core/error.rs
Use safe_network_common v0.1.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/235)
> Version change to 0.13.1

- Cargo.toml
- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
And update other dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/236)
> Migrate to Routing 0.13.0.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/237)
> Version change to 0.14.0

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/238)
> Version change to 0.14.1

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/241)
> Version change to 0.14.2

- Cargo.toml
- examples/client_stress_test.rs
- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/response_getter.rs
- src/core/errors.rs
- src/core/immut_data_operations.rs
- src/core/mod.rs
- src/core/self_encryption_storage.rs
- src/core/structured_data_operations/unversioned.rs
- src/core/structured_data_operations/versioned.rs
- src/dns/dns_operations/mod.rs
- src/lib.rs
- src/nfs/helper/directory_helper.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/242)
> Routing 0.16.1 integration & Immut-Data operations

- examples/client_stress_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/243)
> Extend the client_stress_test to also use structured data.

- src/core/immut_data_operations.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/248)
> fix/immutable-data-op: run immutable data operation test in relase and uncomment test

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/251)
> chore/build: allow rust nightly to fail in travis

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/252)
> chore/deps: update dependencies, use routing 0.19.0

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/255)
> Version change to 0.14.6

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/257)
> Version change to 0.15.0

- Cargo.toml
- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/response_getter.rs
- src/core/client/user_account.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/260)
> refactor/routing: allign with the latest routing

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/261)
> Version change to 0.15.1

- src/ffi/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/264)
> Use Box::{from,into}_raw instead of transmute

- examples/safe_client.rs
- src/core/client/mod.rs
- src/core/self_encryption_storage.rs
- src/core/structured_data_operations/versioned.rs
- src/ffi/mod.rs
- src/nfs/helper/directory_helper.rs
We get stats of every attempt, not only the successful ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/265)
> feat/stats: expose number GETs/PUTs/POSTs/DELETEs

- src/ffi/mod.rs
FFI network event obs thread wrongly called JS callback on even on \'terminated\' event. Corrected by breaking out in that case for graceful thread exit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/268)
> fix/drop: fix exit of background thread in ffi

- src/core/client/mod.rs
- src/core/self_encryption_storage.rs
- src/core/structured_data_operations/unversioned.rs
- src/core/structured_data_operations/versioned.rs
- src/dns/dns_operations/dns_configuration.rs
- src/dns/dns_operations/mod.rs
- src/nfs/helper/directory_helper.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/270)
> Improve DNS error handling

- examples/nfs_api.rs
- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/response_getter.rs
- src/core/client/user_account.rs
- src/core/id/id_type.rs
- src/core/id/public_id_type.rs
- src/core/id/revocation_id_type.rs
- src/core/immut_data_operations.rs
- src/core/structured_data_operations/mod.rs
- src/core/structured_data_operations/unversioned.rs
- src/core/structured_data_operations/versioned.rs
- src/dns/dns_operations/mod.rs
- src/ffi/dns/get_file.rs
- src/ffi/dns/register_dns.rs
- src/ffi/dns/register_public_id.rs
- src/ffi/helper.rs
- src/ffi/launcher_config_handler.rs
- src/ffi/nfs/directory_response.rs
- src/ffi/nfs/file_response.rs
- src/ffi/nfs/move_dir.rs
- src/ffi/nfs/move_file.rs
- src/nfs/directory_listing/mod.rs
- src/nfs/file.rs
- src/nfs/helper/directory_helper.rs
- src/nfs/helper/file_helper.rs
- src/nfs/metadata/directory_metadata.rs
- src/nfs/metadata/file_metadata.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/273)
> refactor/clippy: fix clippy errors

- examples/client_stress_test.rs
- examples/safe_client.rs
- examples/self_authentication.rs
- examples/simulate_browser.rs
- src/core/client/user_account.rs
- src/core/structured_data_operations/mod.rs
- src/core/structured_data_operations/unversioned.rs
- src/core/structured_data_operations/versioned.rs
- src/dns/dns_operations/mod.rs
- src/ffi/dns/delete_dns.rs
- src/ffi/dns/delete_service.rs
- src/ffi/dns/get_file.rs
- src/ffi/helper.rs
- src/ffi/launcher_config_handler.rs
- src/ffi/mod.rs
- src/ffi/nfs/delete_dir.rs
- src/ffi/nfs/modify_file.rs
- src/ffi/nfs/move_dir.rs
- src/ffi/nfs/move_file.rs
- src/nfs/directory_listing/mod.rs
- src/nfs/helper/directory_helper.rs
- src/nfs/helper/file_helper.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/277)
> More clippy fixes.

- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/user_account.rs
- src/ffi/dns/get_file_metadata.rs
- src/ffi/dns/mod.rs
- src/ffi/nfs/get_file_metadata.rs
- src/ffi/nfs/mod.rs
- src/ffi/nfs/move_dir.rs
Fixed issue with move directry api in ffi nfs module
Added new api for fetching file metadata from nfs and dns
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/279)
> fix/ffi_api: resolve move dir api fix

- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/user_account.rs
Low balace cannot be recovered so bail out of recovery process if so instead of wasting cycles and bandwidth
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/280)
> perf/recovery: avoid recovery on low balance

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/281)
> Version change to 0.16.0

- src/core/client/message_queue.rs
- src/core/translated_events.rs
- src/ffi/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/291)
> refactor/logging: add logging on routing disconnects/terminations

- examples/nfs_api.rs
- src/ffi/mod.rs
- src/ffi/nfs/get_file_writer.rs
- src/ffi/nfs/mod.rs
- src/nfs/helper/writer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/293)
> Exposing streaming API to Launcher

- Cargo.toml
- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/response_getter.rs
- src/core/errors.rs
- src/core/translated_events.rs
- src/dns/dns_operations/mod.rs
- src/nfs/metadata/directory_metadata.rs
This implements the client-side portion of the new `GetAccountInfo` Client request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/298)
> feat/account_info: add support for providing client account information

- examples/client_stress_test.rs
- examples/nfs_api.rs
- examples/safe_client.rs
- examples/self_authentication.rs
- examples/simulate_browser.rs
- src/core/client/mod.rs
- src/core/utility/mod.rs
- src/core/utility/test_utils.rs
- src/dns/dns_operations/mod.rs
- src/ffi/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/305)
> Require two credentials from the user

- src/ffi/nfs/modify_dir.rs
- src/ffi/nfs/modify_file.rs
Update modified timestamp while updating metadata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/311)
> fix/ffi_update_modified_time: update modified timestamp for directory and file

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/315)
> Version change to 0.19.0

- Cargo.toml
- rustfmt.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/319)
> Change dylib -> cdylib and tweak rustfmt.toml

- src/ffi/app.rs
- src/ffi/directory_details.rs
- src/ffi/dns/file.rs
- src/ffi/dns/long_name.rs
- src/ffi/dns/service.rs
- src/ffi/file_details.rs
- src/ffi/helper.rs
- src/ffi/logging.rs
- src/ffi/nfs/dir.rs
- src/ffi/nfs/file.rs
- src/ffi/nfs/file_writing.rs
- src/ffi/session.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/321)
> refactor/c_strings: Make use of UTF-8 non-null terminated strings

- Cargo.toml
- src/core/client/message_queue.rs
- src/core/client/mod.rs
- src/core/client/non_networking_test_framework/mod.rs
- src/ffi/app.rs
- src/ffi/directory_details.rs
- src/ffi/errors.rs
- src/ffi/file_details.rs
- src/ffi/helper.rs
- src/ffi/low_level_api/appendable_data.rs
- src/ffi/low_level_api/cipher_opt.rs
- src/ffi/low_level_api/data_id.rs
- src/ffi/low_level_api/immut_data.rs
- src/ffi/low_level_api/misc.rs
- src/ffi/low_level_api/mod.rs
- src/ffi/low_level_api/object_cache.rs
- src/ffi/low_level_api/struct_data.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/324)
> Rfc 0041 low level api Part 1

- src/ffi/directory_details.rs
- src/ffi/low_level_api/appendable_data.rs
- src/ffi/low_level_api/immut_data.rs
- src/ffi/low_level_api/struct_data.rs
- src/ffi/string_list.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/326)
> chore/ffi: replace u64 with usize where it makes sense

- src/ffi/low_level_api/struct_data.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/329)
> test/sruct-data: add tests for structured data with client type tag

- examples/email_stress_test.rs
- src/ffi/app.rs
- src/ffi/low_level_api/appendable_data.rs
- src/ffi/low_level_api/cipher_opt.rs
- src/ffi/low_level_api/data_id.rs
- src/ffi/low_level_api/immut_data.rs
- src/ffi/low_level_api/misc.rs
- src/ffi/low_level_api/object_cache.rs
- src/ffi/low_level_api/struct_data.rs
- tests/email_stress.rs
Fix email-stress-test
Provide new low level apis
Serialisation and deserialisation functions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/332)
> feat/api: new low level apis

- src/ffi/file_details.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/334)
> fix/ffi: fix memory leak in FileDetails::deallocate

- src/core/client/non_networking_test_framework/mod.rs
- src/core/client/non_networking_test_framework/storage.rs
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/330)
> refactor/mock-routing: refactor mock routing

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/336)
> Version change to 0.20.0

- src/ffi/low_level_api/appendable_data.rs
- src/ffi/low_level_api/misc.rs
- src/ffi/low_level_api/object_cache.rs
Including tests for serialisation, removal, and restoration of appendable data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_core/337)
> test/api: add more tests for low-level API

- src/ffi/launcher_config_handler.rs
- src/nfs/dir.rs
- src/nfs/helper/dir_helper.rs
- src/nfs/helper/file_helper.rs
- src/nfs/helper/reader.rs
- src/nfs/helper/writer.rs
- src/nfs/metadata/file_metadata.rs
- src/nfs/mod.rs
* Add tests for file_helper
* Apply fixes for file writer
* Improve tracing/debug info
> refactor/nfs: add tests for file_helper

- src/core/client/account.rs
- src/core/client/mock_routing/mod.rs
- src/core/client/mod.rs
- src/core/client/routing_el.rs
- src/core/core_el.rs
- src/core/errors.rs
- src/core/event.rs
- src/core/mod.rs
- src/core/utility/mod.rs
- src/core/utility/test_utils.rs
- src/lib.rs
Updates client creation functions to use MutableData and a new client authentication scheme for apps (using keys)
> feat/client: update client creation functions

- ffi_utils/src/string.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests.rs
- safe_core/src/ipc/mod.rs
- safe_core/src/ipc/req/ffi.rs
- safe_core/src/ipc/req/mod.rs
- safe_core/src/ipc/resp/mod.rs
This PR covers both MAID-1899 and MAID-1904
> Revoked apps deletion and more authenticator tests

- .travis.yml
- src/ffi/helper.rs
- src/ffi/low_level_api/struct_data.rs
- src/lib.rs
> fix/ffi: fix make_unclaimable for StructuredData

- .travis.yml
- safe_app/src/errors.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/test_utils.rs
- safe_core/Cargo.toml
- safe_core/examples/gen_invites.rs
- safe_core/src/client/account.rs
- safe_core/src/client/mod.rs
- safe_core/src/utils/mod.rs
- safe_core/src/utils/test_utils.rs
> feat/invitation: implement invitation-based account creation

- safe_authenticator/src/ipc.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests.rs
> Safe authenticator revocation fix + tests

- safe_authenticator/src/ipc.rs
- safe_authenticator/src/tests.rs
The app container permissions were not restored when an app was revoked and reauthorised again.
> fix/safe-authenticator: fix revoked app container permissions

- safe_app/Cargo.toml
- safe_app/sample_log_file/log.toml
- safe_app/src/ffi/immutable_data.rs
- safe_app/src/ffi/logging.rs
- safe_app/src/ffi/mod.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_app/src/lib.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/sample_log_file/log.toml
- safe_authenticator/src/ffi/logging.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/lib.rs
- safe_core/Cargo.toml
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mod.rs
* Added logging APIs
* Added FFI APIs to get a serialised size of `MutableData` and `ImmutableData` objects.
> Implement logging APIs (MAID-2085)

- safe_app/src/ffi/mutable_data/tests.rs
- safe_authenticator/src/tests.rs
- safe_core/Cargo.toml
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/client/routing_event_loop.rs
> Mock storage lock

- appveyor.yml
- ffi_utils/src/callback.rs
- ffi_utils/src/macros.rs
- safe_app/src/ffi/access_container.rs
- safe_app/src/ffi/cipher_opt.rs
- safe_app/src/ffi/crypto.rs
- safe_app/src/ffi/helper.rs
- safe_app/src/ffi/immutable_data.rs
- safe_app/src/ffi/mod.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_app/src/ffi/nfs.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/ffi/public_id.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/tests.rs
- safe_core/src/ffi.rs
- safe_core/src/lib.rs
* Expose API to get the account info (used & available mutations)
* Rename functions prefixed with `authenticator_*` to `auth_*`
* Refactor & improve macros in `ffi_utils`
> Expose API to get account info

- safe_app/CHANGELOG.md
- safe_app/Cargo.toml
- safe_authenticator/CHANGELOG.md
- safe_authenticator/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
> Version change

- safe_app/src/ffi/ipc.rs
Jira task MAID-2224. This builds on the earlier #519 work.
Also depends on https://github.com/maidsafe/routing/pull/1505
> Add ffi encoding/decoding functions for ShareMData requests

- safe_authenticator/src/app_auth.rs
- safe_authenticator/src/config.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/revocation.rs
- safe_authenticator/src/test_utils.rs
Supersedes #536 (fix merge conflicts and rebase on latest master)
>  MAID-2199: Address review comments from #518 (updated)

- safe_app/src/ffi/mutable_data/permissions.rs
- safe_app/src/ffi/nfs.rs
1. Add an FFI function to read `PermissionSet` structs given `MDataPermissionSetHandle`.
1. Improve semantics and unify the file_close function behaviour: it returns a modified File struct if a file was opened in one of the write modes, but returned ptr::null() if it was opened in the read mode. This inconsistency is fixed now - we just return an original file struct if a file was opened in the read mode. 
See MAID-2191 for more details.
> Fix file_close behaviour and implement fn to read PermissionSet (MAID-2191 and MAID-2254)

- safe_app/src/ffi/access_container.rs
- safe_app/src/ffi/mutable_data/permissions.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_app/src/ffi/nfs.rs
- safe_app/src/lib.rs
- safe_core/src/ipc/req/mod.rs
Also add more tests for FFI functions
> Refactor access container functions in safe_app (MAID-2268)

- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/permissions.rs
- safe_app/src/ffi/mutable_data/tests.rs
Addresses points 1, 2, 3, 4 and 6 from the Jira task.
> MAID-2334: code cleanup

- README.md
- ffi_utils/src/b64.rs
- ffi_utils/src/lib.rs
- safe_app/src/ffi/ipc.rs
- safe_authenticator/src/ffi/ipc.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/tests/mod.rs
- safe_authenticator/src/tests/share_mdata.rs
- safe_core/src/ipc/mod.rs
Also, update the maintainer to Nikita.
> fix/all: do not require scheme in URIs in safe_auth and safe_app

- safe_core/sample_config/sample.safe_core.config
- safe_core/sample_config/sample_disk.safe_core.config
- safe_core/sample_config/sample_memory.safe_core.config
- safe_core/src/client/mock/account.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/config_handler.rs
- safe_core/src/lib.rs
also add test for new mock-vault path config option
> test/config: add config option for setting mock-vault path

- Cargo.lock
- ffi_utils/Cargo.toml
- ffi_utils/src/b64.rs
- safe_core/Cargo.toml
- safe_core/src/ipc/errors.rs
Also reflect that base64 renamed `Base64Error` to `DecodeError`.
> chore/deps: update base64 version

- safe_authenticator/src/revocation.rs
- safe_authenticator/src/tests/revocation.rs
This should fix https://github.com/maidsafe/beaker-plugin-safe-authenticator/issues/151.
> Fix revocation crash when there are unencrypted entries in the containers

- safe_app/src/ffi/ipc.rs
- safe_authenticator/src/ffi/ipc.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/tests/mod.rs
- safe_authenticator/src/tests/utils.rs
- safe_core/src/ipc/req/mod.rs
- safe_core/src/ipc/resp.rs
+ document missing callback parameters
> feat/ipc: support providing user data in IpcReq::Unregistered

- .travis.yml
+ Add explicit stages to jobs.
+ Reorder `if: type = pull_request` statements.
+ Only run Stable jobs on master branch.
+ Only run `build-binary` if `test-binary` passed.
> chore/ci: fix travis build on master branch

- .travis.yml
- ffi_utils/src/lib.rs
- ffi_utils/src/vec.rs
- safe_app/src/ffi/tests/nfs.rs
Fix the deploy script and republish the built packages.
> Version change: safe_app to 0.8.0; safe_authenticator to 0.8.0; safe_core to 0.31.0;

- safe_authenticator/src/access_container.rs
- safe_authenticator/src/std_dirs.rs
- safe_core/src/client/mdata_info.rs
- safe_core/src/nfs/tests.rs
+ added a test for appending with both small and medium SE instances
+ some minor documentation fixes
>  test/nfs: test writing to files in append mode with different sizes 

- safe_authenticator/src/std_dirs.rs
> fix/auth: add missing _pictures standard directory

- appveyor.yml
- scripts/package.ps1
As with Travis, this introduces a condition at the packaging stage.
I haven't tested this in my own Appveyor namespace because it has a condition on the branch to only run the deployment on master. The automated CI build should tell us if the package is uploaded correctly.
> chore/ci: package based on commit message

- .travis.yml
- safe_app/src/ffi/mod.rs
- safe_app/src/ffi/tests/mod.rs
- safe_authenticator/src/ffi/ipc.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/test_utils.rs
- safe_core/src/ffi/mod.rs
> Replace mock functions and add len parameter to metadata decoding function

- .gitignore
- .travis.yml
- Makefile
- scripts/Jenkinsfile
- scripts/build-with-container
- scripts/package-runner-container
- scripts/package.ps1
- scripts/package.rs
- scripts/test-binary
- scripts/test-runner-container
Rebase & resolve merge conflicts in #733
> SCL Windows Build on Jenkins

- README.md
> Add LoC badge

- .github/ISSUE_TEMPLATE/contributions-guidelines-issue-template.md
Add an issue template which points users to the contribution guidelines documentation.
> chore/Issue: Update issue templates

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Add a pull request template which points users to the contribution guidelines documentation.
> chore/PR: Add PR template

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Moved file locations and updated text in both the issue and PR templates
> chore/templates: update issue and PR templates

- safe_app/examples/client_stress_test.rs
This enables repeat runs of the client_stress_test.
eg ./client_stress_test --locator abcd --password 0123
will run the client_stress_test using the supplied login credentials
This commit also renames secret_0 and secret_1 to their conventional names.
> Allow client_stress_test to login using flags

- safe_authenticator/src/ffi/ipc.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests/share_mdata.rs
>  test/auth: add `share_invalid_mdatas` test 

- Cargo.lock
- safe_app/Cargo.toml
- safe_app/build.rs
- safe_app/src/lib.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/build.rs
- include safe_bindgen as a depdendency only if the bindings feature is enabled
closes #800
> chore/dependencies: make safe_bindgen dependency optional

- safe_app/src/lib.rs
- safe_authenticator/src/lib.rs
- safe_core/src/lib.rs
> chore/clippy: cleanup clippy rules

- .travis.yml
- Cargo.lock
- appveyor.yml
- safe_app/Cargo.toml
- safe_app/src/client.rs
- safe_app/src/lib.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/client.rs
- safe_core/Cargo.toml
- safe_core/src/client/account.rs
- safe_core/src/client/core_client.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/client/routing_event_loop.rs
- safe_core/src/config_handler.rs
- safe_core/src/event.rs
- scripts/build-mock
- scripts/check-all
- scripts/clippy-all
- Add safe-nd depdendency
- Implement send() in mock routing for all client-vault interaction
- Add functions to the mock vault to handle a new data type
- Add put and get functions for the new type to the Client trait with tests
- Introduce BLS key-pair for clients
> Implement new flow for mock routing for new data types

- Makefile
- scripts/Dockerfile.build
- scripts/Jenkinsfile
Hi Nikita,
This is now ready to be merged. The changes here are necessary to run SCL as a 'Multibranch Pipeline' in Jenkins, so any other branches will need to have these changes for the build to be successful.
I've also added a conditional to the deployment so that it'll only run on master.
Cheers,
Chris
> Multi Branch Setup

- Cargo.lock
- safe_app/Cargo.toml
- safe_app/src/errors.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/errors.rs
- safe_core/Cargo.toml
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/errors.rs
feat/mdata: impl Mutable data DELETE RPC function and test
- Fixes breakage of experimental branch by altering function parameters as needed and fixing dependencies.
- Implements converter trait for XorName to facilitate conversion from `routing::XorName` to `safe_nd::XorName`
- Implements required functions for `DELETE` RPC in Mutable Data
> feat/mdata: impl Mutable data DELETE RPC function and test

- Cargo.lock
- safe_core/Cargo.toml
- safe_core/src/client/mock/mod.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
> feat/idata: implement functions for unpublished idata

- mock_routing/src/lib.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mod.rs
- safe_core/src/utils/test_utils/mod.rs
>  test/idata: add more unpub idata tests 

- mock_routing/src/lib.rs
- safe_app/examples/client_stress_test.rs
- safe_app/examples/gen_invites.rs
- safe_app/examples/self_authentication.rs
- safe_app/src/errors.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/test_utils.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/errors.rs
- safe_core/src/event.rs
- safe_core/src/ipc/mod.rs
- safe_core/src/ipc/resp.rs
- safe_core/src/lib.rs
- safe_core/src/nfs/errors.rs
- scripts/clippy-mock
- scripts/clippy-real
- tests/src/lib.rs
> chore/clippy: clean up clippy rules

- Cargo.lock
- safe_app/src/errors.rs
- safe_app/src/tests/coins.rs
- safe_authenticator/src/errors.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- Add API to load a wallet with test safecoin
- Add optional SecretKey field for safecoin operations
- Gracefully return an error when trying to fetch a non-existent entry in MData
resolves #842 #843 #852 #850
> Add safecoin features and fix GetMDataValue

- Cargo.lock
- safe_app/src/errors.rs
- safe_authenticator/src/errors.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
> Use common response type for mutation requests

- Cargo.lock
- mock_routing/Cargo.toml
- mock_routing/src/lib.rs
- safe_app/Cargo.toml
- safe_app/examples/client_stress_test.rs
- safe_app/src/errors.rs
- safe_app/src/ffi/tests/mod.rs
- safe_app/src/lib.rs
- safe_app/src/tests/unpublished_mutable_data.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/client.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/ffi/mod.rs
- safe_core/Cargo.toml
- safe_core/src/client/mock/mod.rs
- safe_core/src/client/mock/routing.rs
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/event.rs
- safe_core/src/immutable_data.rs
- safe_core/src/self_encryption_storage.rs
- tests/Cargo.toml
- tests/src/lib.rs
See https://github.com/maidsafe/safe-nd/pull/47
> refactor/data: refactor the new data types based on safe-nd changes

- Cargo.lock
- safe_app/src/ffi/access_container.rs
- safe_app/src/ffi/mdata_info.rs
- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_app/src/tests/unpublished_mutable_data.rs
- safe_authenticator/src/access_container.rs
- safe_authenticator/src/app_container.rs
- safe_authenticator/src/apps.rs
- safe_authenticator/src/client.rs
- safe_authenticator/src/config.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/revocation.rs
- safe_authenticator/src/std_dirs.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests/mod.rs
- safe_authenticator/src/tests/revocation.rs
- safe_authenticator/src/tests/serialisation.rs
- safe_core/src/client/account.rs
- safe_core/src/client/mdata_info.rs
- safe_core/src/client/mod.rs
- safe_core/src/ffi/mod.rs
- safe_core/src/ipc/resp.rs
- safe_core/src/nfs/dir.rs
- safe_core/src/nfs/file_helper.rs
- safe_core/src/nfs/tests.rs
- tests/src/real_network.rs
> refactor/mdata: refactor MDataInfo to use MDataAddress and MDataKind

- Cargo.lock
- mock_routing/Cargo.toml
- safe_app/Cargo.toml
- safe_app/src/errors.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/src/errors.rs
- safe_core/Cargo.toml
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
Also make necessary changes to make SCL work with latest changes in the safe-nd API.
> chore/deps: update safe-nd and self-encryption

- safe_core/src/client/core_client.rs
- safe_core/src/client/mod.rs
> Replace CreateLoginPacketFor with CreateLoginPacket in CoreClient

- safe_authenticator/src/client.rs
> Add test for create_login_packet_for flow

- safe_app/src/tests/mod.rs
> Add test to ensure that anyone can read published data

- Cargo.lock
- safe_app/src/client.rs
- safe_authenticator/src/client.rs
- safe_core/src/client/core_client.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
> feat/vault: add `sign` field to `compose_message`

- Cargo.lock
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/connection_manager.rs
- safe_core/src/connection_manager/connection_group.rs
> add handling for Challenge flow

- Cargo.lock
- mock_routing/Cargo.toml
- safe_app/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_core/Cargo.toml
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- tests/Cargo.toml
> chore/deps: update safe-nd to 0.2.0

- safe_app/src/ffi/crypto.rs
- safe_app/src/ffi/test_utils.rs
- safe_app/src/ffi/tests/mod.rs
- safe_authenticator/src/client.rs
- safe_authenticator/src/revocation.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator/src/tests/revocation.rs
- safe_core/src/client/core_client.rs
- safe_core/src/client/mod.rs
- safe_core/src/ffi/ipc/req.rs
- safe_core/src/ffi/ipc/resp.rs
- safe_core/src/ffi/nfs.rs
- safe_core/src/ipc/mod.rs
- safe_core/src/ipc/req/mod.rs
- safe_core/src/ipc/resp.rs
- safe_core/src/nfs/file_helper.rs
> chore/all: make small improvements to documentation

- Cargo.lock
- safe_core/Cargo.toml
- safe_core/src/client/mock/vault.rs
> Use tempfile storage in tests

- safe_app/src/client.rs
- safe_app/src/tests/append_only_data.rs
- safe_app/src/tests/mod.rs
- safe_authenticator/src/client.rs
- safe_core/src/client/mod.rs
- safe_core/src/connection_manager.rs
- safe_core/src/connection_manager/connection_group.rs
> Use a unique quic-p2p for each ConnectionGroup

- Cargo.lock
- Makefile
- safe_core/src/client/mock/connection_manager.rs
- safe_core/src/client/mock/vault.rs
- scripts/Jenkinsfile
- scripts/test-with-mock-vault-file
> chore/deps: update to safe-nd 0.3.2

- safe_core/src/client/mock/account.rs
- safe_core/src/client/mock/connection_manager.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
> Some refactors and fixes in the mock vault with relevant tests

- safe_app/src/tests/mod.rs
- safe_authenticator/src/app_auth.rs
- safe_authenticator/src/client.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/tests/mod.rs
- safe_authenticator/src/tests/revocation.rs
- safe_core/src/client/mock/connection_manager.rs
> feat/hooks: fixes hooks functionality

- Makefile
- safe_app/src/client.rs
- safe_authenticator/src/tests/mod.rs
- safe_core/src/client/mock/connection_manager.rs
- safe_core/src/client/mock/vault.rs
- safe_core/src/client/mod.rs
- safe_core/src/ipc/mod.rs
- safe_core/src/lib.rs
apps should connect using the bootstrap config from the auth response to
bootstrap to the network
> Use the bootstrap config from the auth response and add a cost for create balance

- safe_authenticator/src/lib.rs
> Make some required modules public

- Makefile
- scripts/Jenkinsfile
Due to compilation during the packaging process, we discovered that it's actually quite slow to publish a crate. Will be much faster to do 3 in parallel.
> chore/ci: publish crates in parallel

- safe_authenticator/src/access_container.rs
- safe_authenticator/src/config.rs
- safe_authenticator/src/errors.rs
- safe_authenticator/src/ffi/mod.rs
- safe_authenticator/src/ipc.rs
- safe_authenticator/src/lib.rs
- safe_authenticator/src/test_utils.rs
> doc/auth: add missing docs

- Cargo.lock
- safe_app/Cargo.toml
- safe_app/build.rs
- safe_app/src/ffi/mdata_info.rs
- safe_app/src/ffi/mutable_data/entries.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_app_jni/src/lib.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/build.rs
- safe_authenticator/src/test_utils.rs
- safe_authenticator_jni/src/lib.rs
- safe_core/src/client/mdata_info.rs
- safe_core/src/ffi/arrays.rs
- safe_core/src/ffi/mod.rs
- safe_core/src/ipc/req/mod.rs
- tests/src/real_network.rs
Fixes https://github.com/maidsafe/safe_client_libs/issues/1008
> fix/jni: fix safe_app and safe_auth jni builds

- safe_app/Cargo.toml
- safe_app_jni/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_authenticator_jni/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- scripts/Jenkinsfile
- tests/Cargo.toml
Hi Nikita,
Can you just give this a quick check to make sure I've done this correctly please?
Cheers,
Chris
> Version change: safe_core to 0.34.0

- Cargo.lock
- safe_app/Cargo.toml
- safe_app_jni/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_authenticator_jni/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- tests/Cargo.toml
> Version change: safe_core to 0.35.0

- safe_core/src/config_handler.rs
> fix/config_handler: fix appending `/config` when custom setting config path

- .github/workflows/master.yml
- .github/workflows/pr.yml
> chore/ci: add missing clippy/rustfmt job and env vars

- .github/workflows/master.yml
- .github/workflows/pr.yml
- README.md
- safe_core/src/client/mock/mod.rs
- safe_core/src/config_handler.rs
- safe_core/src/connection_manager/connection_group.rs
- scripts/test-mock
1. Update Readme to display result of last Master build (and fix the Issues badge)
2. Fix deploy steps not being version-change-gated
3. Remove `SAFE_MOCK_IN_MEMORY_STORAGE` from the `tests` job (would cause the `config_mock_vault_path` test to fail once that is re-enabled)
4. Use the `test-mock` script in the `test` job
> chore/ci: make misc fixes in GHA workflows and readme

- .github/workflows/master.yml
Put "Master" workflow steps in correct order, fixing error in deploy with deploy
directories not existing
> fix/ci: fix deploy in Github Actions

- .github/workflows/master.yml
- scripts/clippy-mock
- scripts/clippy-real
- scripts/get-release-description
> chore/ci: make GitHub Actions improvements

- .github/workflows/master.yml
- .github/workflows/pr.yml
- Cargo.lock
- safe_app/Cargo.toml
- safe_app/build.rs
- safe_app_jni/src/lib.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/build.rs
- safe_authenticator_jni/src/lib.rs
- safe_core/Cargo.toml
Depends on https://github.com/maidsafe/safe_bindgen/pull/56, which fixes issue with https://github.com/maidsafe/safe_client_libs/pull/1068
> fix/build: fix cargo build issues and add to GHA

- safe_app/Cargo.toml
- safe_app/build.rs
- safe_app/src/cipher_opt.rs
- safe_app/src/client.rs
- safe_app/src/errors.rs
- safe_app/src/ffi/cipher_opt.rs
- safe_app/src/ffi/crypto.rs
- safe_app/src/object_cache.rs
- safe_authenticator/Cargo.toml
- safe_authenticator/build.rs
- safe_authenticator/src/client.rs
- safe_core/src/client/account.rs
- safe_core/src/client/core_client.rs
- safe_core/src/client/mod.rs
- safe_core/src/crypto.rs
- safe_core/src/ffi/arrays.rs
- safe_core/src/ffi/ipc/resp.rs
- safe_core/src/ipc/errors.rs
- safe_core/src/ipc/resp.rs
Rebased on top of #1096 
Resolves #1081
> Migrate Asymmetric encryptions from rust_sodium to threshold_crypto

- Cargo.lock
- safe_app/CHANGELOG.md
- safe_app/Cargo.toml
- safe_app_jni/Cargo.toml
- safe_authenticator/CHANGELOG.md
- safe_authenticator/Cargo.toml
- safe_authenticator_jni/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- tests/Cargo.toml
> Version change: safe_core to 0.37.0; safe_authenticator to 0.12.0; safe_app to 0.12.0

- .github/workflows/master.yml
- scripts/get-release-description
> chore/ci: fix development build links in release description

- .github/workflows/master.yml
- .github/workflows/pr.yml
- safe_authenticator/src/client.rs
> chore/ci: fix automatic publishing

- Cargo.lock
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
> Version change: safe_core to 0.37.2

- .github/workflows/master.yml
- Cargo.lock
- safe_app/Cargo.toml
- safe_app_jni/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_authenticator_jni/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- tests/Cargo.toml
> Version change: safe_core to 0.37.3

- .github/workflows/master.yml
- .github/workflows/pr.yml
- Makefile
> chore/ci: use cargo lipo to generate universal iOS fat libs

- .github/workflows/master.yml
- scripts/package-runner
> chore/ci: fix iOS static libs deployment issue

- Cargo.lock
- safe_app/Cargo.toml
- safe_app/src/ffi/immutable_data.rs
- safe_app/src/ffi/mod.rs
- safe_app/src/ffi/mutable_data/entry_actions.rs
- safe_app/src/ffi/mutable_data/mod.rs
- safe_app/src/ffi/mutable_data/tests.rs
- safe_app/src/ffi/nfs.rs
- safe_app/src/ffi/tests/nfs.rs
- safe_app/src/tests/mod.rs
- safe_authenticator/Cargo.toml
- safe_core/Cargo.toml
- safe_core/src/errors.rs
- safe_core/src/utils/logging/mod.rs
- tests/Cargo.toml
Closes #713
Depends on https://github.com/maidsafe/safe-nd/pull/140
> feat/app: add support for GET_NEXT_VERSION in more places

- safe_authenticator/src/app_auth.rs
- safe_authenticator/src/apps.rs
- safe_authenticator/src/config.rs
- safe_authenticator/src/ffi/apps.rs
- safe_authenticator/src/tests/mod.rs
> refactor/ffi: make RegisteredApp struct include AppPermissions

- .github/workflows/master.yml
Note: This PR may change based on further replies to [this thread](https://github.community/t5/GitHub-Actions/Use-a-job-level-conditional-if-to-check-command-output/m-p/42911/highlight/false#M5170).
> chore/ci: use job-level if to condition on version change commit

- .github/workflows/master.yml
- .github/workflows/pr.yml
> chore/ci: use correct yaml tag for mac and resolve invalid yaml issue

- safe_app/src/lib.rs
- safe_authenticator/src/lib.rs
- safe_core/src/ffi/mod.rs
- safe_core/src/lib.rs
Supersedes #1136 and closes #1065
> Add documentation for export strategy

- Cargo.lock
- safe_app/Cargo.toml
- safe_app_jni/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_authenticator_jni/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- tests/Cargo.toml
> Version change: safe_core to 0.38.1

- safe_authenticator/src/client.rs
> refacor/client: refactor unnecessary disconnect during account creation.

- safe_app/build.rs
- safe_authenticator/build.rs
- safe_authenticator/src/app_auth.rs
- safe_authenticator/src/apps.rs
- safe_authenticator/src/config.rs
- safe_authenticator/src/tests/revocation.rs
> Do not store AppPermissions in the client's config root

- safe_app/build.rs
- safe_authenticator/build.rs
- safe_authenticator/src/app_auth.rs
- safe_authenticator/src/apps.rs
- safe_authenticator/src/client.rs
- safe_authenticator/src/config.rs
- safe_authenticator/src/tests/revocation.rs
- safe_core/src/config_handler.rs
- safe_core/src/connection_manager.rs
Contains changes from the fleming branch that are compatible for a phase 1 update.
> Updates to the master branch.

- safe_app/src/ffi/immutable_data.rs
- safe_core/src/immutable_data.rs
- safe_core/src/nfs/data_map.rs
> add postition and index to get_value

- safe_core/src/connection_manager/connection_group.rs
This makes GET requests faster :)
> Don't wait for all vaults to respond to GET requests

- .github/workflows/master.yml
- .github/workflows/pr.yml
> Disable Android and iOS builds on CI

- safe_app/src/errors.rs
- safe_app/src/ffi/errors/mod.rs
- safe_authenticator/src/errors.rs
- safe_core/src/errors.rs
- safe_core/src/ipc/errors.rs
- safe_core/src/self_encryption_storage.rs
- safe_core/src/utils/logging/mod.rs
> Remove use of Error::description()

- Cargo.lock
- safe_app/CHANGELOG.md
- safe_app/Cargo.toml
- safe_app_jni/Cargo.toml
- safe_authenticator/CHANGELOG.md
- safe_authenticator/Cargo.toml
- safe_authenticator_jni/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- tests/Cargo.toml
> Update ffi utils

- .github/workflows/master.yml
- .github/workflows/pr.yml
- Cargo.lock
- safe_core/Cargo.toml
- safe_core/src/config_handler.rs
- scripts/package-runner
> enable mobile builds with the latest quic-p2p

- scripts/package-runner
> chore/ci: fix package-runner script

- safe_app/src/client.rs
- safe_authenticator/src/client.rs
- safe_core/src/client/core_client.rs
- safe_core/src/client/mod.rs
- safe_core/src/connection_manager.rs
> Do multiple bootstrap attempts before returning an error

- .github/workflows/master.yml
- Cargo.lock
- safe_app/CHANGELOG.md
- safe_app/Cargo.toml
- safe_authenticator/CHANGELOG.md
- safe_authenticator/Cargo.toml
- safe_authenticator_ffi/CHANGELOG.md
- safe_authenticator_ffi/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- scripts/package-runner
- tests/Cargo.toml
safe_authenticator to 0.15.0, safe_authenticator_ffi to 0.15.0
> Version change: safe_core to 0.40.0, safe_app to 0.15.0,

- .github/workflows/master.yml
- .github/workflows/pr.yml
- scripts/get-release-description
- scripts/package-runner
- scripts/package.ps1
> refactor/ci: remove safe_app builds and refactor builds

- .github/workflows/master.yml
- Cargo.lock
- safe_app/Cargo.toml
- safe_authenticator_ffi/README.md
> feat/ffi: add safe_auth_ffi for mock-network feature

- Cargo.lock
- safe_app/Cargo.toml
- safe_authenticator_ffi/LICENSE
- tests/Cargo.toml
> Version change: safe_app to 0.15.1

- safe_app/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_authenticator_ffi/src/lib.rs
- safe_core/src/ffi/ipc/resp.rs
> chore/ffi: minor ffi refactoring changes

- safe_core/src/connection_manager/connection_group.rs
- safe_core/src/connection_manager/connection_hook_manager.rs
- safe_core/src/connection_manager/mod.rs
- safe_core/src/connection_manager/response_manager.rs
Dont rely on last response only.
Adds a connection hook manager for easier testing
adds tests
> Use most common responses

- scripts/generate_dependency_graphs
Currently getting an error when the deploy of the updated png file is attempted by CI
https://github.com/maidsafe/safe_client_libs/runs/674604164?check_suite_focus=true#step:5:10
```
Starting to commit changes…
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌
Deployment Failed
```
I'm not 100% clear why this error is occurring but I made a couple of tweaks in my fork & the deploy works fine there - see [here](https://github.com/S-Coyle/safe_client_libs/actions/runs/104674193). Pushing upstream to see if resolves it here as well
> fix(ci): fix dependency graph script

- Cargo.lock
- safe_app/examples/client_stress_test.rs
- safe_core/Cargo.toml
- safe_core/src/client/mock/tests.rs
- safe_core/src/client/mod.rs
- safe_core/src/connection_manager/connection_group.rs
> chore/deps: update quic-p2p to 0.6.2 and some new clippy fixes

- Cargo.lock
- safe_app/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_authenticator_ffi/Cargo.toml
- safe_core/Cargo.toml
- tests/Cargo.toml
> refactor(deps): standardise cargo dependency versioning

- safe_core/src/client/mod.rs
- safe_core/src/client/transfer_actor/balance_management.rs
- safe_core/src/client/transfer_actor/write_apis.rs
- safe_core/src/connection_manager/connection_group.rs
> tests/updates: fix various testa nd update checks for at2

- Cargo.lock
- safe_app/Cargo.toml
- safe_authenticator/Cargo.toml
- safe_authenticator_ffi/Cargo.toml
- safe_core/Cargo.toml
- tests/Cargo.toml
> update multiple dependencies

- Cargo.lock
- safe_app/CHANGELOG.md
- safe_app/Cargo.toml
- safe_authenticator/CHANGELOG.md
- safe_authenticator/Cargo.toml
- safe_core/CHANGELOG.md
- safe_core/Cargo.toml
- tests/Cargo.toml
> Version change: safe_app to 0.18.0, safe_core to 0.43.0, safe_authenticator to 0.18.0

- Cargo.lock
- src/client/blob_apis.rs
- src/client/mod.rs
- src/utils/mod.rs
- src/utils/test_utils/mod.rs
...when the Client is created
- also applies rustfmt
> Fix logging by using initializing env_logger

- Cargo.lock
- Cargo.toml
- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/write_apis.rs
- src/utils/mod.rs
- src/utils/test_utils/mod.rs
- tests/src/lib.rs
> tests: export tests

- Cargo.lock
- Cargo.toml
- src/client/mod.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/config_handler.rs
- src/connection_manager.rs
- src/errors.rs
> New qp2p and listeners

- .github/workflows/master.yml
- .github/workflows/pr.yml
- .github/workflows/security_audit.yml
Updated version of the checkout action being used to v2.
Tidied and condensed the caching.
Removed some unnecessary use of the cargo action, switching to
use the cargo command instead.
Supersedes #1232
> refactor(ci): Refactor of GHA CI files

- README.md
- scripts/generate_dependency_graphs
Updated to reflect recent changes to this crate
> Update dependencies graph generation & readme display

- Cargo.lock
- Cargo.toml
- src/client/transfer_actor/balance_management.rs
- src/connection_manager.rs
> fix(qp2p): Fixes for latest qp2p master

- CHANGELOG.md
- scripts/generate_dependency_graphs
- src/client/blob_storage.rs
- src/self_encryption_storage.rs
Note that I checked clippy locally & there were a load (30+) warnings to be resolved, but none related to this PR's changes.
Had a go at resolving but unsure of some of the changes, e.g. when the recommendation states `if this is intentional...`, so leaving for a Rust dev
> chore(deps): update to reference renamed self_encryption repo

- .github/workflows/pr.yml
- src/client/blob_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
> ci(build): fix build test

- sample_config/safe_core.default.config
- src/config_handler.rs
> chore(refactor) removed quicp2p our-type config option

- Cargo.lock
- Cargo.toml
- scripts/generate_dependency_graphs
- src/client/mod.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/write_apis.rs
> chore(deps): update to reference renamed sn_transfers crate

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- src/lib.rs
> Fix broken links in the documentation

- src/client/blob_apis.rs
- src/client/blob_storage.rs
- src/client/map_apis.rs
- src/client/map_info.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/config_handler.rs
- src/crypto.rs
- src/errors.rs
- src/lib.rs
- src/network_event.rs
- src/self_encryption_storage.rs
- src/utils/logging/async_log.rs
- src/utils/logging/web_socket.rs
- src/utils/mod.rs
- src/utils/test_utils/mod.rs
- src/utils/test_utils/sync.rs
> Fix doc tests

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- scripts/generate_dependency_graphs
- src/client/blob_apis.rs
- src/client/blob_storage.rs
- src/client/map_apis.rs
- src/client/map_info.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/client/transfer_actor/write_apis.rs
- src/connection_manager.rs
- src/errors.rs
- src/self_encryption_storage.rs
- src/utils/test_utils/mod.rs
- src/utils/test_utils/sync.rs
> Feat update data types

- .gitignore
- Cargo.lock
- Cargo.toml
- src/connection_manager.rs
> chore: quic-p2p -> quic_p2p

- Cargo.lock
- Cargo.toml
- sample_config/safe_core.default.config
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/config_handler.rs
- src/connection_manager.rs
- src/errors.rs
- src/lib.rs
> Fix update deps

- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/connection_manager.rs
> Fix client startup

- README.md
- src/utils/test_utils/sync.rs
> chore(deps): update to reference renamed sn_routing

- src/client/mod.rs
> fix(test): don't hide exported tests behind #[cfg(test)]

- Cargo.lock
- src/client/mod.rs
- src/client/transfer_actor/mod.rs
- src/connection_manager.rs
> Client Event Listener setup

- src/connection_manager.rs
> feat(errors): add error for insufficient elder connections

- src/client/transfer_actor/mod.rs
- src/config_handler.rs
> fix/config: update config for sn_node renaming

- Makefile
> chore(node): update to reference renamed sn_node

- Cargo.lock
- src/client/transfer_actor/mod.rs
- src/connection_manager.rs
> Feat retry bootstrap

- Cargo.lock
- Cargo.toml
- src/client/blob_apis.rs
- src/client/mod.rs
- src/config_handler.rs
- src/lib.rs
- src/utils/logging/async_log.rs
- src/utils/logging/mod.rs
> feat(blob): expose self_ecnrypt API for dry run

- Cargo.lock
- Cargo.toml
- src/connection_manager.rs
> chore(deps): updates for latest safe_nd

- Cargo.lock
- Cargo.toml
- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/client/transfer_actor/write_apis.rs
- src/lib.rs
> client instatiate from fullids

- Cargo.lock
- Cargo.toml
- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/connection_manager.rs
- src/utils/mod.rs
> Aggregate SignatureShares for AT2 transfers and multiple fixes

- .github/workflows/pr.yml
- Cargo.lock
- Cargo.toml
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/client/transfer_actor/write_apis.rs
- src/connection_manager.rs
- src/lib.rs
- src/utils/test_utils/mod.rs
> Remove ClientFullIds/PublicIds conceptually

- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/connection_manager.rs
> refactor(tests): export transfers tests for sn_node

- Cargo.lock
- Cargo.toml
- src/client/sequence_apis.rs
- src/client/transfer_actor/write_apis.rs
This depends on https://github.com/maidsafe/sn_data_types/pull/260
> chore(Sequence): adapt to changes in Sequence data type API

- Cargo.lock
- Cargo.toml
> Update qp2p version 

- Cargo.lock
- Cargo.toml
- src/client/sequence_apis.rs
- src/client/transfer_actor/write_apis.rs
> feat(seq): Use signed ops for sequence append

- Cargo.lock
- Cargo.toml
- src/config_handler.rs
- src/connection_manager.rs
> feat(qp2p): update qp2p version

- Cargo.lock
- src/client/blob_storage.rs
- src/client/sequence_apis.rs
- src/self_encryption_storage.rs
> tests: fix seq basic test expectations

- src/connection_manager.rs
> chore(elders): update count to expect 5 as standard

- Cargo.lock
- Cargo.toml
- src/client/blob_apis.rs
- src/client/blob_storage.rs
- src/client/transfer_actor/mod.rs
- src/connection_manager.rs
- src/utils/test_utils/mod.rs
> Update to new version of sn_data_types and sn_tranfers

- Cargo.lock
- Cargo.toml
- src/client/sequence_apis.rs
> feat(seq): Sign ops before applying locally + sending to network

- src/client/sequence_apis.rs
> fix(seq): sign op.crdt_op

- Cargo.toml
- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/connection_manager.rs
- src/errors.rs
> feat(err_listener): implement CmdError listener and fix map data tests

- src/client/mod.rs
- src/client/sequence_apis.rs
- src/connection_manager.rs
> feat: remove seq cache

- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/client/transfer_actor/write_apis.rs
- src/lib.rs
> Feat(arc): Require an arc wrapped keypair for init

- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/client/transfer_actor/write_apis.rs
- src/lib.rs
> feat: add configurable bootstrap to client

- Cargo.lock
- Cargo.toml
- src/client/mod.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
> tests: improve tests, and update qp2p

- Cargo.lock
- Cargo.toml
- src/client/sequence_apis.rs
> feat: update lseq data type

- .github/workflows/master.yml
Still had references to old steps, and old release commit message.
> chore(cd): fix CD pipeline `Deploy` step

- .github/workflows/master.yml
- CHANGELOG.md
- Cargo.toml
> Fix CD build stage, update changelog and adjust previously incorrect v numbers

- .github/workflows/master.yml
- scripts/package-runner
Some leftover references to dev and mobile from the previous release process.
> chore(cd): remove dev and mobile references from CD pipeline

- Cargo.lock
- src/client/blob_apis.rs
- src/client/mod.rs
> feat(blob): remove local blob cache

- Cargo.lock
- src/client/mod.rs
- src/connection_manager.rs
- src/errors.rs
- remove listener locks
- remove connect_to_elder func to simplify retries there.
> chore(refactor): Remove some locks and simplify connection management

- .github/workflows/pr.yml
- Cargo.lock
- sample_config/sn_client.default.config
- src/connection_manager.rs
- src/errors.rs
> Chore update deps and fix clippy

- src/client/sequence_apis.rs
This removes the need to call get_sequence_range(address, (index, index+1))
This change is a prerequisite to removing the use of `get_sequence_range` when fetch a single sequence entry (which is in [this part of the source code](https://github.com/maidsafe/sn_api/blob/67b746f607501511c38fe752f64119a12985ab72/sn_api/src/api/app/safe_client.rs#L491-L495)).
The response is consistent with `get_sequence_last_entry`
Not sure if fetching from too high a version should give the latest, or should throw an error. Considering `in_range` allows versions higher than the number available (not explicitly but as a side effect), I went with an equivalent concept here. Returning the actual version allows the user to know if they've requested a version too high and deal with it in their own way. I imagine …
> Add get_sequence_at_version method

- .github/workflows/pr.yml
- Cargo.lock
- Cargo.toml
- scripts/check-all
- scripts/clippy-all
- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/client/transfer_actor/write_apis.rs
> chore: remove unneeded exported tests

- Cargo.lock
- Cargo.toml
- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/crypto.rs
- src/utils/test_utils/mod.rs
Updates for reward flow changes across sn_* repos.
> Rewards flow

- .github/workflows/master.yml
- .github/workflows/pr.yml
- Cargo.lock
- Cargo.toml
- src/client/map_apis.rs
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/client/transfer_actor/write_apis.rs
- src/connection_manager.rs
- src/lib.rs
> Chore updatefor dt and transfers

- .github/workflows/pr.yml
- Cargo.lock
- src/client/map_apis.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/lib.rs
> fix: doc tests

- .github/workflows/master.yml
- .github/workflows/pr.yml
> chore(cicd): Update cache action version to v2.1.4

- .github/workflows/pr.yml
> chore(ci): add PR size check to CI

- Cargo.toml
- src/connection_manager.rs
> Update to the latest qp2p API

- .github/workflows/pr.yml
> chore(ci): update pr_size_checker to v2

- sample_config/sn_client.default.config
- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/connection_manager.rs
> Fix force wait for keys

- src/client/transfer_actor/mod.rs
- src/connection_manager.rs
> feat(elders): remove hard coded elder count

- src/client/transfer_actor/mod.rs
- src/errors.rs
> fix: threshold and error text

- Cargo.toml
- src/client/mod.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/connection_manager.rs
- src/errors.rs
> chore: dep updates and changes for split

- src/client/mod.rs
- src/client/sequence_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/simulated_payouts.rs
- src/connection_manager.rs
> Improvements to Connection Management 1

- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/write_apis.rs
- src/config_handler.rs
- src/connection_manager.rs
- src/errors.rs
- src/utils/test_utils/test_client.rs
+ add unknown client error handling
> feat: use known vs all elders, supermajority

- src/connection_manager.rs
> Clean up client connections when elders change

- src/connection_manager.rs
> fix(bootstrap): fix bootstrap logic when we get SectionInfo::Redirect

- Cargo.toml
> Update qp2p version

- Cargo.toml
- src/config_handler.rs
- src/connection_manager.rs
> Fix logging in conn

- .gitignore
- src/config_handler.rs
- src/connection_manager.rs
> fix: create listeners before sending queries

- src/client/mod.rs
> Use public address to sign and send bootstrap request

- Cargo.toml
- src/connection_manager.rs
> Add timeout around connect_to

- Cargo.toml
> chore(deps): update xor_name to 1.2.0

- src/connection_manager.rs
Even when we send a query to only a subset of our elders, all the elders that we are connected to can respond back to us. This change allows the client to accept the response from any of it's elders instead of just the ones we contacted.
> Accept query responses from all Elders

- src/client/blob_apis.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/connections/listeners.rs
- src/connections/messaging.rs
> refactor(logs): make log messages less noisy

- src/client/map_apis.rs
- src/client/mod.rs
- src/client/transfer_actor/mod.rs
- src/connections/listeners.rs
- src/connections/messaging.rs
- src/connections/mod.rs
> feat(errors): receive CmdErrors from the network

- .github/workflows/e2e.yml
- src/client/transfer_actor/balance_management.rs
- src/utils/test_utils/test_client.rs
> ci: make e2e run on all platforms

- .github/workflows/e2e.yml
- src/client/blob_apis.rs
- src/client/map_apis.rs
- src/client/transfer_actor/mod.rs
- src/utils/test_utils/mod.rs
> More test improvements

- src/connections/listeners.rs
- src/connections/messaging.rs
- src/connections/mod.rs
> fix(query): timeout when we don't get a response for a query

- Cargo.toml
- src/connections/listeners.rs
- src/connections/messaging.rs
> chore: update qp2p dep

- .github/workflows/e2e.yml
- src/client/mod.rs
- src/client/transfer_actor/balance_management.rs
- src/client/transfer_actor/mod.rs
- src/client/transfer_actor/write_apis.rs
- src/connections/listeners.rs
- src/connections/messaging.rs
- src/connections/mod.rs
> Concurrency updates

- examples/blob.rs
- src/connections/messaging.rs
> feat: discard blob errors if we get a positive one instead

- Cargo.toml
- examples/blob.rs
- src/client/blob_apis.rs
- src/client/map_apis.rs
> fix: use tokio 1.6, 1.7 seems buggy
